### PR TITLE
Cache index on disk

### LINKED ISSUE #47: Cache indexing result
Currently the project index is rebuilt from scratch every time the workspace is opened.
This can take a long time during which features might not work properly.

We need a file system cache for the results of the indexing process.

### PR DESCRIPTION
**Pull request by felixfbecker**
Closes #47

This is a very simple implementation of a disk cache. 
When index finished and on shutdown the definitions and references are saved to `.phpls/definitions.json` and `.phpls/references.json`.
On initialization, they are restored before beginning to reindex.
No fancy cache invalidation.
The result is when you once indexed a project, the second time you open it you can use all features instantly without having to wait for indexing to finish.

Magento:
```
[Info  - 02:07:26] Saving 203562 definitions to cache
[Info  - 02:07:26] Saving 323550 references to cache
```

### CODE REVIEW

**Comment by mniewrzal** [comment]
Indexing is still triggered after restoring cache.

File: src/LanguageServer.php [hunk 1]
```diff
@@ -157,14 +167,69 @@ private function indexProject(string $rootPath)
...
 
         Loop\setTimeout($processFile, 0);
     }
+
+    /**
+     * Restores the definition and reference index from the .phpls cache directory, if available
+     *
+     * @return void
+     */
+    public function restoreCache()
```
Comment (mniewrzal) [inline src/LanguageServer.php]: I think this method can return true if both 'definitions' and 'references' are restored correctly. If one of them is missing then cache is invalid.

Comment (felixfbecker) [inline src/LanguageServer.php]: And what would that return value be used for?

**Comment by felixfbecker** [comment]
@mniewrzal that is intended. It is just for having some feature support in the first minute of indexing there already, but then quickly update the index and cache. A lot can happen to files while the LS is not running, user can switch branches etc. and I don't want to deal with cache invalidation at this point.

**Comment by mniewrzal** [comment]
Ok, I understand your conception now. Ignore my comment to restoreCache method :)

Works ok on my machine :)

**Comment by felixfbecker** [comment]
Thanks for testing. Anyone else objections? @kaloyan-raev @levan-g @MadHed

**Comment by kaloyan-raev** [comment]
No objections. If it's ok for @mniewrzal then it is ok for me too :)

**Comment by MadHed** [comment]
Works for me. Is there a standard for where to store per-workspace extension metadata?
I thought these would go into .vscode.

**Comment by mniewrzal** [comment]
> On second thought... since this project will be used by other IDEs maybe .vscode would not be so great :D

Exactly ;)
