### PR TITLE
Caching

### LINKED ISSUE #47: Cache indexing result
Currently the project index is rebuilt from scratch every time the workspace is opened.
This can take a long time during which features might not work properly.

We need a file system cache for the results of the indexing process.

### PR DESCRIPTION
**Pull request by felixfbecker**
Closes #47 

Implements the [cache extension](https://github.com/sourcegraph/language-server-protocol/blob/68c291281db65eb41ad9890e71c962bda92b5e03/extension-chache.md) and alternatively falls back to the file system.
Cache directory is `~/.phpls` on Linux/Mac and `%LOCALAPPDATA%/PHP Language Server` on Windows.

The index for each dependency gets serialized and saved in the cache, keyed by package name and version.

Indexing is now done by the `Indexer` class.

### CODE REVIEW

File: src/Cache/ClientCache.php [hunk 1]
```diff
@@ -0,0 +1,48 @@
...
+    /**
+     * Sets a value in the cache
+     *
+     * @param string $key
+     * @param mixed  $value
+     * @return Promise
+     */
+    public function set(string $key, $value): Promise
+    {
+        return $this->client->xcache->set($key, serialize($value))->otherwise(function () {
```
Comment (staabm) [inline src/Cache/ClientCache.php]: Serialze has a lot of security implications and is slow. You should consider using e.g. json_encode, igbinary or similar

Comment (felixfbecker) [inline src/Cache/ClientCache.php]: What security implications does it have? `json_encode` would be magnitudes _slower_ because it does not store the class info, I would have to copy all properties into class instances. `serialize` output is also much smaller than `json_encode`.

Comment (staabm) [inline src/Cache/ClientCache.php]: serialize had dozens of security related problems in the past
https://www.google.de/search?q=php+serialize+cve

using serialize() will also mean your cache contents will be coupled to the class definitions (and future updates can make the contents inconsistent with future class definitions).

Comment (staabm) [inline src/Cache/ClientCache.php]: what do you mean by "the class info"?

Comment (felixfbecker) [inline src/Cache/ClientCache.php]:
```php
class MyClass {
  myMethod() {}
}
json_decode(json_encode(new MyClass))->myMethod() // not defined
```

Comment (felixfbecker) [inline src/Cache/ClientCache.php]: Re: Security. The security concerns all revolve around `unserialize` triggering autoloading and `__wakeup` calls of unwanted classes, if the serialized content has been tempered with and then relies on the presence of a class that would actually cause harm. For this, you would need to have access to the cache. If an attacker has access to the `~/.phpls`, he has write access to your user folder already, which means he could do a lot worse stuff than tampering with a PHP LS cache. And he also already has access to `~/.vscode/extensions`, which means instead of trying to inject an attack in the cache, he could just modify the PHP source in place, which would be much easier, can do a lot more harm and there is nothing we can do against it.

If, on the other hand, the cache is stored inside the client, then it is his responsibility to secure it.

> using serialize() will also mean your cache contents will be coupled to the class definitions (and future updates can make the contents inconsistent with future class definitions).

That's why all cache items are prefixed with a version. The cache format will eventually change at some point, whether I use JSON or `serialize`, it needs to be versioned.

Comment (staabm) [inline src/Cache/ClientCache.php]: you can either do stuff on your own:
https://3v4l.org/5Y60r

or use libs which provide this kind of functionality, e.g:
http://jmsyst.com/libs/serializer

Re Security: your class doesnt know whether the content beeing stored is provided by user-input or not.

> That's why all cache items are prefixed with a version. The cache format will eventually change at some point, whether I use JSON or serialize, it needs to be versioned.
nice!

Comment (felixfbecker) [inline src/Cache/ClientCache.php]: I am already using JSONMapper in the project for all LSP communications. _But it is slow_. Because you need to parse JSON, then iterate over all the properties _recursively_, use reflection to parse and check the `@var` tags of the classes to see what type they are, instantiate that class (which, btw, is also remote code execution), copy all properties values over, continue. `unserialize` is much, much faster for this.

> Re Security: your class doesnt know whether the content beeing stored is provided by user-input or not.

If you are referring to the `Cache` class, no, and it's not its job. Its job is to save and get cache items in serialized form. It's not its job to implement any security layer. The cache store is trusted, it is a database, _not_ user input. You don't sanitize values that come from your own database, you secure your database properly.

Comment (staabm) [inline src/Cache/ClientCache.php]: I guess we can agree to disagree ;-).

Comment (felixfbecker) [inline src/Cache/ClientCache.php]: The mapping with the algorithm I described is what makes it slow. And that is needed, because I need class instances of `Definition`, `Index` etc, not `\stdClass`

**Comment by jrobeson** [comment]
can the cache directory be configurable? I'd like to use my linux native `$XDG_CACHE_HOME` (usually `~/.cache`.

**Comment by felixfbecker** [comment]
@jrobeson There isn't any configuration in the language server, but if the env var is defined, I would default it to `$XDG_CACHE_HOME/phpls`. Sounds good?

**Comment by jrobeson** [comment]
I'd appreciate it, thanks :)

File: src/Indexer.php [hunk 2]
```diff
@@ -0,0 +1,222 @@
...
+            $count = count($uris);
+            $startTime = microtime(true);
+            $this->client->window->logMessage(MessageType::INFO, "$count files total");
+
+            /** @var string[] */
+            $source = [];
+            /** @var string[][] */
+            $deps = [];
+            foreach ($uris as $uri) {
+                if ($this->composerLock !== null && preg_match('/\/vendor\/([^\/]+\/[^\/]+)\//', $uri, $matches)) {
```
Comment (wulftone) [inline src/Indexer.php]: I think this directory should be pulled from `composer.json`--not everyone uses the default `./vendor/` directory and they are missing out on these wonderful cache benefits.

Comment (felixfbecker) [inline src/Indexer.php]: Feel free to do a PR

File: src/Cache/FileSystemCache.php [hunk 3]
```diff
@@ -0,0 +1,67 @@
...
+class FileSystemCache implements Cache
+{
+    /**
+     * @var string
+     */
+    public $cacheDir;
+
+    public function __construct()
+    {
+        if (PHP_OS === 'Windows') {
```
Comment (jens1o) [inline src/Cache/FileSystemCache.php]: Don't use PHP_OS here, since it is just the system php was built from, not the system it is running at the moment. Use PHP_EOL instead(`\r\n` is typical for Windows)
