### PR TITLE
Adopt Microsoft/tolerant-php-parser

### LINKED ISSUE #323: Microsoft/tolerant-php-parser adoption
As discussed in https://github.com/Microsoft/tolerant-php-parser/issues/36#issuecomment-274563749, key benefits include:
* graceful error handling
* performance + memory usage
* fully-representative tree

I'm currently working with Felix to put together a functional prototype. This would be a pretty major change, there may be some temporary regressions, and we will certainly need to make some improvements to the parser before it's ready for primetime. 

This issue acts as a catch-all to track progress on that work.

<hr/>

## Current status:
**_Working branch:_**
* _Language server: https://github.com/felixfbecker/php-language-server/compare/master...mousetraps:tolerant_
* _Parser: https://github.com/Microsoft/tolerant-php-parser/compare/master...mousetraps:lang-server_

### Features
- [x] error diagnostics
- [x] find all symbols
- [x] find all symbols in workspace
- [x] **_[not impacted]_** format code
- [x] go to definition
- [x] find all references
- [x] hover
- [ ] completion

### Known regressions
* Error diagnostics produced by the parser are not currently "strict" because we parse things more loosely in order to provide error tolerance, so we won't get diagnostics for everything until we add relevant post-parse checks (this will happen on the parser side).
* The new parser has higher granularity when it comes to Node position info, which results in slightly different (but still correct) position locations in some cases (for instance for a function call `hello(/*cursor*/)`, go-to-definition at the denoted cursor position will not yield a result (but will yield a result if the function call name is selected)
* The new parser does not have pretty-printing yet, so the definition lines produced are exactly what the user has typed in (including whitespace), rather than a pretty-printed version.
* Magic constants are treated like normal constants and will therefore appear in "find all references" results. Their fqsen will be resolved to their namespace value if one is defined (even though this is not actually legal).
* true, false, and null are not included in find all references results (which is probably the expected behavior anyways)
* variables used within template strings are not currently included in find all references results
* _TODO_

### Related parser issues
Parser work for this next milestone is [tracked here](https://github.com/Microsoft/tolerant-php-parser/milestone/2). Any additional issues that should be prioritized?

### PR DESCRIPTION
**Pull request by mousetraps**
fix #323

As discussed in https://github.com/Microsoft/tolerant-php-parser/issues/36#issuecomment-274563749, key benefits include:
* graceful error handling
* performance + memory usage
* fully-representative tree

This is a pretty big PR, so in order to make it easier to review - a little explanation of the current status and deep dive into the changes is in order. Additionally, this braindump was a good way to wrap my head around the remaining issues :smiley:. Happy to answer any additional Qs, and stay tuned for further updates!

### What's ready for review? 
* The files that are ready for code review right now are **`TolerantDefinitionResolver.php`** and **`TolerantSymbolInformation.php`**. There are still a few TODOS, Formatting and doc comments need some clean up, but otherwise pretty reasonable.
* Additionally, it would be helpful to get **feedback on general approach.** As described below, the code itself still needs a lot of cleanup, and can be misleading. I plan to work through these remaining issues in the coming days. 

<hr>

I'll walk through this in two stages:
1. Some general status
2. Some context around the code changes themselves (including TODOs on each file, which I'll make my way through tomorrow). Note that I'm still working on cleaning this up, so sorry that it's a currently quite unpolished and/or potentially misleading.

## General Status
**_Working branch:_**
* _Language server: https://github.com/felixfbecker/php-language-server/compare/master...mousetraps:tolerant_
* _Parser: https://github.com/Microsoft/tolerant-php-parser/compare/master...mousetraps:lang-server_

### Currently implemented Features
- [x] error diagnostics
- [x] find all symbols
- [x] find all symbols in workspace
- [x] [not impacted] format code
- [x] go to definition
- [x] find all references
- [x] hover
- [ ] completion

### Testing and Validation
In order to validate the changes, I thoroughly compared the language server results (fqns, definitions, references) of the two parsers on a number of frameworks (~15,000 files in total), and worked to resolve any discrepencies.
- [x] CakePHP
- [x] Drupal
- [x] math-php
- [x] php-language-server
- [x] tolerant-php-parser
- [x] symfony
- [x] Wordpress

#### Notable Improvements
- Errors are now gracefully handled
- Significantly improved performance
- fully representatative trees, which means it'll be suitable for formatting / refactoring operations
- proper of Qualified Names in more places (e.g. catch expression types now resolve propery)
- function return types are properly resolved to a type
- use Trait references are now properly resolved
- group function use declarations are now properly resolved to a type
- improved namespace reference part references

#### Notable Regressions
- Error diagnostics produced by the parser are not currently "strict" because we parse things more loosely in order to provide error tolerance, so we won't get diagnostics for everything until we add relevant post-parse checks (this will happen on the parser side).
- The new parser does not have pretty-printing yet, so the definition lines produced are exactly what the user has typed in (including whitespace), rather than a pretty-printed version.
- Magic constants are treated like normal constants and will therefore appear in "find all references" results. They will also not be included in type resolution. Their fqsen will be resolved to their namespace value if one is defined (even though this is not actually legal).
- variables used within template strings are not currently included in find all references results [requires parser fix]
- yield-expressions support (currently produces squigglies on "yield", but rest of tree is OK) [requires parser fix]

#### Other differences
* The new parser has higher granularity when it comes to Node position info, which results in slightly different (but still correct) position locations in some cases (for instance for a function call `hello(/*cursor*/)`, go-to-definition at the denoted cursor position will not yield a result (but will yield a result if the function call name is selected)

#### Performance Comparison
At this point in time, the performance is not nearly as good as it could be (e.g. every call to getResolvedName does a tree walk rather than performing any caching, does not include the impacts of incremental parsing, some of the API or API calls are innefficient and need to be improved).

That said, even **_without_** these changes - some preliminary results of the impact from the most recent run  - this includes all lang. server operations, not just are below (see Performance.php for details - only ran this on my machine - PHP 7.1 x64 on Windows, kept an eye on CPU to ensure it remained constant throughout, units are in seconds) - still need to run more benchmarks and analayze results (unfortunately XDebug profiler has been seriously failing me for this use case): 

| Framework | old parser | new parser | % difference | notes | 
| --------- | ---------- | ---------- | ------------ | ------|
| drupal    | 35.1       | 25.7       |     -27%      |       |
| wordpress | 3.2        | 2.1        |     -34%      |       | 
| php-language-server | 12.6 | 9.6 |        24%         |       | 
| tolerant-php-parser | 3.2 | 5.0 | +56% | results incomplete - old parser produced null ASTs for 146 files and significantly fewer definitions overall |
| math-php | 1.5 | 0.9 | -40%  | |
| symfony | 17.3 | 12.1 | -30% | |
| CodeIgniter | 1.5 | 1.0 | -33% | |
| cakephp | 4.5 | 3.4 | -24% | | 

The memory improvements are not nearly as significant as they could be because at this point in time, only the ASTs for the open files are held in memory, and definitions/references representation is the primary concern. However as demonstrated earlier - the ASTs themselves are significantly lighter, so in the future, we could hold many more in memory rather than throwing them all away.

### Next steps
- [ ] Finish cleaning up existing code
- [ ] Merge updates from master
- [ ] Implement completions support
- [ ] Merge parser changes into master (see https://github.com/Microsoft/tolerant-php-parser/compare/master...mousetraps:lang-server)
- [ ] Complete remaining parser changes
- [ ] Update extension and distribute early version for people to play with
- [ ] Fuzz-testing

## File Changes
Changes described below, with corresponding TODOs

#### GENERAL TODO
- [ ] add `declare(strict_types = 1);` to all files
- [ ] clean up doc comments, add comments for new method definitions
- [ ] clean up formatting
- [ ] revert all files not mentioned below

### composer.json [modified]
Modified to add a reference Microsoft/tolerant-php-parser. Note that the referenced version is currently being pulled from a private branch until these changes make their way to master

#### TODO 
- [ ] modify to pull from `lang-server` rather than `dev-lang-server` branch
- [ ] update to official branch when available, consider distributing through package manager instead. 

### LanguageServer.php [modified]
The language server entrypoint is at `LanguageServer::initialize()`. The `initialize` method is responsible for setting up the indexes, server capabilities, etc. 

The changes here are pretty minimal. The first change is that the $definitionResolver property is now of type `DefinitionResolverInterface`, rather than `DefinitionResolver`.

This enables us to hotswap parsers - `DefinitionResolver` (the definition resolver corresponding to the old parser) and `TolerantDefinitionResolver` (the definition resolver corresponding to the new parser) both implement `DefinitionResolverInterface`

### DefinitionResolverInterface.php [added], DefinitionResolver.php [modified], TolerantDefinitionResolver.php [modified]
In order to make it as easy as possible to transition from the old parser to the new parser and validate these changes, they both retain the same core interface as before: 
- getDeclarationLineFromNode($node)
- getDocumentationFromNode($node)
- createDefinitionFromNode($node, string $fqn = null) : Definition
- resolverReferenceNodeToDefinition($node)
- resolveExpressionNodeToType($expr) : Type
- getTypeFromNode($node)
- getDefinedFqn($node)

The signatures no longer include type hints for `PhpParser\Node` - this is because the new Node objects of are type `Microsoft\PhpParser\Node` (note that `Microsoft\PhpParser` is aliased as `Tolerant` everywhere)

The `TolerantDefinitionResolver` logic has been completely rewritten otherwise to support the new AST structure and node / token properties.

Initially, I considered creating some more granular abstractions in the hopes of creating a shared interface between the two parsers, but the differences were too significant to be worth the effort (e.g. method calls are significantly more expensive than property accesses, code became more difficult to debug, etc.)

#### TODO
- [ ] finish reviewing type resolution logic for expressions
- [ ] revert functional changes to `DefinitionResolver`

### ParserResourceFactory.php [added], ParserKind.php [added]
The ParserResourceFactory class enables us to manage the resources between the two parser kinds (defined in ParserKind). This includes instantiating the parser, definition resolver, and tree analyzers.

The parser kind is set with a static property, and there are two primary parser kinds
- `PHP_PARSER`
- `TOLERANT_PHP_PARSER`

The current 'default' is `TOLERANT_PHP PARSER`. 

In addition, there are diagnostic modes which can be accessed by specifying `DIAGNOSTIC_PHP_PARSER`, or `DIAGNOSTIC_TOLERANT_PHP_PARSER`. The main difference is that when these values are specified, they will instantiate a `LoggedDefinitionResolver` or `LoggedTolerantDefinitionResolver` instead of `DefinitionResolver` or `TolerantDefinitionResolver`

#### TODO
- [ ] static property rather than global (and update all other scripts / files)

### LoggedDefinitionResolverTrait.php [added], LoggedDefinitionResolver.php [added], LoggedTolerantDefinitionResolver.php [added]
`LoggedDefinitionResolver` and `LoggedTolerantDefinitionResolver` are basic wrappers around `DefinitionResolver` and `TolerantDefinitionResolver` to make it easier to debug the application without explicitly attaching a debugger, and the actual logging logic is defined in `LoggedDefinitionResolverTrait`. Currently, logs are simply printed out to the console, but in the future we could implement some more advanced logging.

The logs themselves are pretty basic - they intercept the primary method calls, and log their corresponding signatures, input parameters, and returned results. In addition, they are indented according to their current level of recursion. 

In the future, it might be helpful to include more granular logging, but this has been sufficient for now (note that there would also be a performance impact to keeping this logging on all the time). 

There are also a few logging options worth mentioning (the *way* they are implemented is currently pretty hacky and specific to a particular problem I was investigating, but this can be revisited). `maxRecursion` keeps track of the max recursion level (an interesting statistic for diagnosing issues - could also consider using a formal cap on this to prevent CPU spinning out of control). `repeat` number of times a method should be repeated - I used this to diagnose some issues when I realized that the XDebug profiler results were absolutely useless for this application (by repeating a method call many times, I was able to get more accurate time stamps when analyzing perf. issues). `times` keeps track of the timing profiles

#### TODO
- [ ] rename `Logged` -> `Diagnostic`
- [ ] some object types are being rendered as UNKNOWN - figure out if there's a consistent way to render these
- [ ] consider removing or changing representation of `maxRecursion`, `repeat`, and `times` properties
- [ ] update or remove printLogs

### ReferencesCollector.php [modified], DefinitionCollector.php [modified]
These files have been updated to correspond with the new DefinitionResolver interfaces

#### TODO
- [ ] refer to definition resolver rather than FqnUtilities 

### FqnUtilities.php [added]
For holding some common logic between the two definition resolvers.

#### TODO
- [ ] remove getDefinedFqn (and update references to refer to definition resolver instead)
- [ ] revisit definition resolver logic, and determine additional candidates to pull into this shared set of utilities
- [ ] rename to DefinitionResolutionUtilities

### Location.php [modified], Range.php [modified]
Modified to support creating locations and ranges from both node types.

#### TODO
- [ ] Extract Range::fromNode and Range::fromLocation DefinitionResolutionUtilities file
- [ ] consider returning better representation from parser

#### TODO
- [ ] replace getFirstAncestor call with call to TolerantParserHelpers::tryGetPropertydeclaration

### TolerantParserHelpers.php [added]
A temporary class to assist in answering simple questions about the AST. Eventually these operations will be rendered redundant by the parser.

#### TODO
- [ ] update parser APIs to better represent these operations instead
- [ ] better naming form methods (e.g. `tryGetPropertyDeclarationFromVariable`)

### TreeAnalyzerInterface.php [added], TreeAnalyzer.php [added], TolerantTreeAnlayzer.php [added]
Central interface for performing definition / reference collection. One thing that's worth mentioning is that - for performance reasons, I didn't end up taking advantage of the built-in Node API of the tolerant parser, but will revisit this decision.

#### TODO
- [ ] better naming
- [ ] review and clean up logic
- [ ] revist parser API around this

### TextDocument.php [modified]
Responsible for handling TextDocument requests from client and server (e.g. definition, references). Updated logic to properly handle new node types and definition resolver interface

#### TODO
- [ ] review and clean up logic
- [ ] refactor to more clearly reflect old/new parser code paths

### Tests/* [modified]
Many of the tests have been updated to account for updated node locations. Unfortunatley this breaks tests for the first parser. 

#### TODO
- [ ] consider a way to not break tests for the other parser
- [ ] review modfied tests for correctness
- [ ] consider clearer testing strategy

### ValidationTest.php [added], broken/*.php [added]
Validation tests used to validate the parser against the old parser. broken/*.php are cases that were at some point an issue during the validation run (but not during the main run)

#### TODO
- [ ] majorly update validation test logic (currently super hacky)
- [ ] revisit and reorganize broken/*.php tests, better naming all around
- [ ] consider converting validation tests that compare one parser against another to tests that compare the results of the parser against the old results of the parser on the same set of files to better detect regressions
- [ ] add more submodules
- [ ] update travis run to include tests
- [ ] update phpunit.xml to include multiple test groups

### CODE REVIEW

**Comment by jens1o** [comment]
wow.

File: src/TolerantDefinitionResolver.php [hunk 1]
```diff
@@ -0,0 +1,880 @@
...
+        } else {
+            $defLine = clone $node;
+        }
+        // Don't include the docblock in the declaration string
+        $defLine->setAttribute('comments', []);
+        if (isset($defLine->stmts)) {
+            $defLine->stmts = [];
+        }
+        $defText = $this->prettyPrinter->prettyPrint([$defLine]);
+        return strstr($defText, "\n", true) ?: $defText;
```
Comment (jens1o) [inline src/TolerantDefinitionResolver.php]: `strstr` is **really** slow, why aren't you use `strpos`, which also consumes less-memory?

File: src/TolerantDefinitionResolver.php [hunk 2]
```diff
@@ -0,0 +1,880 @@
...
+            $fn = $node->getAttribute('parentNode');
+            $docBlock = $fn->getAttribute('docBlock');
+            if ($docBlock !== null) {
+                $tags = $docBlock->getTagsByName('param');
+                foreach ($tags as $tag) {
+                    if ($tag->getVariableName() === $node->name) {
+                        return $tag->getDescription()->render();
+                    }
+                }
+            }
```
Comment (jens1o) [inline src/TolerantDefinitionResolver.php]: you're missing parameter type hinting?

```php
<?php
new class {

    public function __construct(SomeClass $foo) {
         // $foo is a instance of SomeClass
    }
};

File: src/TolerantDefinitionResolver.php [hunk 3]
```diff
@@ -0,0 +1,880 @@
...
+        if ($node instanceof Node\Stmt\PropertyProperty || $node instanceof Node\Const_) {
+            $node = $node->getAttribute('parentNode');
+        }
+        if ($node instanceof Node\Param) {
+            $fn = $node->getAttribute('parentNode');
+            $docBlock = $fn->getAttribute('docBlock');
+            if ($docBlock !== null) {
+                $tags = $docBlock->getTagsByName('param');
+                foreach ($tags as $tag) {
+                    if ($tag->getVariableName() === $node->name) {
```
Comment (jens1o) [inline src/TolerantDefinitionResolver.php]: Check first wether `$tag` isn't null?

File: src/TolerantDefinitionResolver.php [hunk 4]
```diff
@@ -0,0 +1,880 @@
...
+            $node instanceof Node\Name && (
+                $parent instanceof Node\Stmt\ClassLike
+                || $parent instanceof Node\Param
+                || $parent instanceof Node\FunctionLike
+                || $parent instanceof Node\Stmt\GroupUse
+                || $parent instanceof Node\Expr\New_
+                || $parent instanceof Node\Expr\StaticCall
+                || $parent instanceof Node\Expr\ClassConstFetch
+                || $parent instanceof Node\Expr\StaticPropertyFetch
+                || $parent instanceof Node\Expr\Instanceof_
```
Comment (jens1o) [inline src/TolerantDefinitionResolver.php]: maybe sort all the if-statements after commonly use? So things that are used the most are sooner found? Could be a difference for huge projects.

File: src/TolerantDefinitionResolver.php [hunk 5]
```diff
@@ -0,0 +1,880 @@
...
+                    }
+                }
+                // If it is a closure, also check use statements
+                if ($n instanceof Node\Expr\Closure) {
+                    foreach ($n->uses as $use) {
+                        if ($use->var === $name) {
+                            return $use;
+                        }
+                    }
+                }
```
Comment (jens1o) [inline src/TolerantDefinitionResolver.php]: :+1: This is missing currently.

File: src/TolerantDefinitionResolver.php [hunk 6]
```diff
@@ -0,0 +1,880 @@
...
+        return (string)$classNode->namespacedName;
+    }
+
+    /**
+     * Returns the assignment or parameter node where a variable was defined
+     *
+     * @param Node\Expr\Variable|Node\Expr\ClosureUse $var The variable access
+     * @return Node\Expr\Assign|Node\Expr\AssignOp|Node\Param|Node\Expr\ClosureUse|null
+     */
+    public static function resolveVariableToNode(Node\Expr $var)
```
Comment (jens1o) [inline src/TolerantDefinitionResolver.php]: Maybe check also for `foreach`/`for` variables?

File: src/TolerantDefinitionResolver.php [hunk 7]
```diff
@@ -0,0 +1,880 @@
...
+            || $expr instanceof Node\Expr\Cast\Double
+        ) {
+            return new Types\Float_;
+        }
+        if ($expr instanceof Node\Expr\Array_) {
+            $valueTypes = [];
+            $keyTypes = [];
+            foreach ($expr->items as $item) {
+                $valueTypes[] = $this->resolveExpressionNodeToType($item->value);
+                $keyTypes[] = $item->key ? $this->resolveExpressionNodeToType($item->key) : new Types\Integer;
```
Comment (jens1o) [inline src/TolerantDefinitionResolver.php]: why do you fall back to an integer?

File: src/PhpDocument.php [hunk 8]
```diff
@@ -284,11 +247,21 @@ public function getNodeAtPosition(Position $position)
         if ($this->stmts === null) {
             return null;
         }
-        $traverser = new NodeTraverser;
-        $finder = new NodeAtPositionFinder($position);
-        $traverser->addVisitor($finder);
-        $traverser->traverse($this->stmts);
-        return $finder->node;
+
+        if (\is_array($this->stmts)) {
```
Comment (jens1o) [inline src/PhpDocument.php]: this slash is worrying and not needed?

File: src/TolerantDefinitionResolver.php [hunk 9]
```diff
@@ -0,0 +1,1177 @@
...
+        // Static methods and static property declarations
+        $def->isStatic = (
+            ($node instanceof Tolerant\Node\MethodDeclaration && $node->isStatic()) ||
+
+            (($propertyDeclaration = TolerantParserHelpers::tryGetPropertyDeclaration($node)) !== null
+            && $propertyDeclaration->isStatic())
+        );
+
+        if ($node instanceof Tolerant\Node\Statement\ClassDeclaration &&
+            // TODO - this should be bette rrpreented in the parser API
```
Comment (jens1o) [inline src/TolerantDefinitionResolver.php]: What does this mean?

File: src/TolerantDefinitionResolver.php [hunk 10]
```diff
@@ -0,0 +1,1177 @@
...
+
+        // STRING EXPRESSIONS: resolve to Types\String
+        //   [concatenation] .=, .
+        //   [literals] "hello", \b"hello", \B"hello", 'hello', \b'hello', HEREDOC, NOWDOC
+        //   [cast] (string) "hello"
+        //
+        //   TODO: Magic constants (__CLASS__, __DIR__, __FUNCTION__, __METHOD__, __NAMESPACE__, __TRAIT__, __FILE__)
+        if (
+            ($expr instanceof Tolerant\Node\Expression\BinaryExpression &&
+                ($expr->operator->kind === Tolerant\TokenKind::DotToken || $expr->operator->kind === Tolerant\TokenKind::DotEqualsToken)) ||
```
Comment (jens1o) [inline src/TolerantDefinitionResolver.php]: You're missing the comma token, it's supported by php(but slow):
`echo 'Hello', ' World; // => Hello World`

File: src/TolerantDefinitionResolver.php [hunk 11]
```diff
@@ -0,0 +1,1177 @@
...
+            $expr instanceof Tolerant\Node\StringLiteral ||
+            ($expr instanceof Tolerant\Node\Expression\CastExpression && $expr->castType->kind === Tolerant\TokenKind::StringCastToken)
+        ) {
+            return new Types\String_;
+        }
+
+        // BINARY EXPRESSIONS: 
+        // Resolve to Types\Integer if both left and right operands are integer types, otherwise Types\Float
+        //   [operator] +, -, *, **
```
Comment (jens1o) [inline src/TolerantDefinitionResolver.php]: maybe resolve also `pow` as a function? Afaik, there is also a function for multiple.

File: src/TolerantDefinitionResolver.php [hunk 12]
```diff
@@ -0,0 +1,1177 @@
...
+            $node instanceof Tolerant\Node\Statement\TraitDeclaration
+        ) {
+            return (string) $node->getNamespacedName();
+        }
+
+        // INPUT                   OUTPUT:
+        // namespace A\B;           A\B
+        else if ($node instanceof Tolerant\Node\Statement\NamespaceDefinition && $node->name instanceof Tolerant\Node\QualifiedName) {
+            $name = (string) Tolerant\ResolvedName::buildName($node->name->nameParts, $node->getFileContents());
+            return \count($name) > 0 ? $name : null;
```
Comment (jens1o) [inline src/TolerantDefinitionResolver.php]: slash worries again. (see also next if statement)

File: src/TolerantDefinitionResolver.php [hunk 13]
```diff
@@ -0,0 +1,1177 @@
...
+
+            // Instance Property: use ClassName->propertyName as name
+            return (string)$classDeclaration->getNamespacedName() . '->' . $name;
+        }
+
+        // INPUT                        OUTPUT
+        // namespace A\B;
+        // const FOO = 5;               A\B\FOO
+        // class C {
+        //   const $a, $b = 4           A\B\C::$a(), A\B\C::$b
```
Comment (jens1o) [inline src/TolerantDefinitionResolver.php]: Why is `$a` a function?

File: tests/Validation/ValidationTest.php [hunk 14]
```diff
@@ -0,0 +1,241 @@
...
+
+        $directory = __DIR__ . "/output/$frameworkName/";
+        $outFile = $directory . basename($testCaseFile);
+
+        try {
+            $document = new PhpDocument($testCaseFile, $fileContents, $index, $parser, $docBlockFactory, $definitionResolver);
+        } catch (\Exception $e) {
+            if (!file_exists($dir = __DIR__ . "/output")) {
+                mkdir($dir);
+            }
```
Comment (jens1o) [inline tests/Validation/ValidationTest.php]: You should check wether it is writeable and try to change it with `chmod`.

File: tests/Validation/ValidationTest.php [hunk 15]
```diff
@@ -0,0 +1,241 @@
...
+    /**
+     * @group validation
+     * @dataProvider frameworkErrorProvider
+     */
+    public function testDefinitionErrors($testCaseFile, $frameworkName) {
+        $fileContents = file_get_contents($testCaseFile);
+        echo "$testCaseFile\n";
+
+        $parserKinds = [ParserKind::DIAGNOSTIC_PHP_PARSER, ParserKind::DIAGNOSTIC_TOLERANT_PHP_PARSER];
+        $parserKinds = [ParserKind::PHP_PARSER, ParserKind::TOLERANT_PHP_PARSER];
```
Comment (jens1o) [inline tests/Validation/ValidationTest.php]: redefinition of same variable?

**Comment by felixfbecker** [comment]
Just went through the diff and figured it would be better to write up a general review instead of commenting on the diff. The implementation of the parser-using code LGTM overall and are less than I expected.

### DefinitionResolverInterface / Dual parser support
As I understand it, this was added to allow the LS to switch parsers on demand. I don't know whether it is worth to keep this capability. I understand that it made it easier to compare changes and performance to the existing implementation, but I believe the tolerant parser is just objectively better and I don't see a benefit in allowing to switch it or keeping around any code for the old parser. Some things bother me about the interface:
- Technically, none of the DefinitionResolver implementations implement the interface. The methods are declared as taking `Tolerant\Node | PhpParser\Node` (which obviously have different interfaces), but the implementations only accept one of them and would error if you pass the other. So there isn't really common interface besides matching method names, the expected parameters are different. 
- As I understand it, this is then worked around by having a global variable that a static factory uses to determine the parser and DefinititionResolver to use (so the two match). So on the one hand it decouples the LS from a parser, but on the other hand it introduces coupling between components through global state

Given this (and the added complexity), do you see any benefit in keeping the old DefinitionResolver implementation around and allowing this kind of drop-in DefinitionResolver replacement?

DefinitionResolver as it is (in master) is not following SoC very well - it resolves definitions to references, references to definitions and also acts as a factory for Definition objects. The same is true for `SymbolInformation` - since I didn't have a use case for creating SymbolInformation from different kind of nodes, I just added a static factory method. There should not be multiple `SymbolInformation` classes just for the purpose of having different factories. Supporting multiple parsers therefor definitely increases complexity.

#### Optimization
What kind of caching did you have in mind? A map from node -> definition? Isn't that basically what the Index does?

### Logging/Tracing
Classic cross-cutting concern. Sooner or later this had to be added to the LS, but it should follow some standard way.

For logging, there is the [PSR-3 standard](http://www.php-fig.org/psr/psr-3/), which provides interfaces for loggers. Classes that perform logging should implement the `LoggerAwareInterface` which allows to set a Logger. This favours composition over inheritance (no need for `LoggedFooBar` classes). I would then also add an implementation of `LoggerInterface` that logs over LSP `window/logMessage`.

Tracing should be done through OpenTracing - this is on my todo list. There is no official base implementation for PHP, but https://github.com/Wikia/opentracing-php looks pretty good. I would get in contact with the OpenTracing members to get something official together. For now, it seems like you got by with logging quite well, but I would take care not to reimplement too much logic that is better done by just plugging in an OpenTracing implementation.

### Types
In the future, I would like to get rid of the phpDocumentor dependency and would suggest that we integrate some docblock parsing into tolerant parser and classes that represent types.

### Keeping ASTs in memory
The reason why I only keep indexes in memory is that these contain just the information needed to respond to the currently supported operations. The `Definition` class is not optimised at all though, it mostly keeps raw LSP structures in memory. Instead, it could only carry the minimal data needed to _build_ LSP structures (probably removing some duplicated data). Definition instances are serialized as part of Index instances to disk (or the xcache LSP extension) for caching and for the stdlib stubs - if we only worked with ASTs, then the cache would be as big as the source code since the AST represents all parts of the source code. It probably would also fail to serialise because of the cyclic parent node references (except if they implemented Serialisable in some advanced way).

### Incremental parsing
I was very fascinated by the use of Iterators and Generators in tolerant parsers. How can these functionalities be used in the LS, what changes would be needed, where do you see the best potential improvement?

### Regressions
How much work do you think is left for
- hovers with (pretty-printed) fully qualified names (instead of local names)?
- completions?
- yield support?

### Release plan
After this is merged, I would just tag a prerelease version, then also tag a prerelease version on vscode-php-intellisense and put a vsix on the GitHub release page to try it out easily. 

I would also like to keep this initial PR as small as possible to get it into master as early as possible and then do other improvements later.

This is awesome work! 👏

**Comment by mousetraps** [comment]
Thanks for the feedback! I'll iterate further on the PR. Responses below:

> Given this (and the added complexity), do you see any benefit in keeping the old DefinitionResolver implementation around and allowing this kind of drop-in DefinitionResolver replacement?

Not particularly - as you mentioned, the main benefits were threefold:
1. make it easier to bootstrap from the previous parser, which has had much more exposure
2. serve as a good baseline on performance
3. make it easier to merge earlier and enable a longer "tranisition period" in the event that there were significant gaps

These goals have been achieved, so I agree we should just remove the interface. 

> What kind of caching did you have in mind? A map from node -> definition? Isn't that basically what the Index does?

I think we're overloading the term here, so to clarify what I meant to say... in the previous implementation, name resolution would occur during the tree walk (provided by the NameResolver visitor). This means that context about previously encountered namespaces and namespace use declarations (and thereby aliases) was built up node-by-node. The results were stored one the Nodes of the AST, and therefore be available at any moment through a property fetch (`namespacedName` or `name`). In the new parser, no information is stored on the Nodes of the AST. This means that every call to `getResolvedName` traverses up to the containing namespace, and iterates through namespace use declarations up to the current node to build up the import tables. This represents a significant duplication of effort given how frequently `getResolvedName` is called, so I suspect that streamlining this process would yield significant perf improvements.

As far as the Index goes, let's set up some time to discuss this in depth. I have some ideas, but they're not in a particularly consumable form just yet. 

> Logging/Tracing

Thanks for the pointers- I wasn't aware of those standards. And mea culpa - in this case, by "logging", I meant "tracing" (which is why I wanted to change the name to use "Diagnostic" rather than "Log"). I think that the current functionality is a valuable start (significantly speeds up iteration time), even if doesn't follow the OpenTracing standard. Would you be okay merging that in (with cleanup described above re: DefinitionResolverInterface and in TODOs) and then opening a separate issue to track OpenTracing? Alternatively, this might be a good candidate to split into a separate PR so we can keep this one as small as possible.  

> In the future, I would like to get rid of the phpDocumentor dependency and would suggest that we integrate some docblock parsing into tolerant parser and classes that represent types.

Agreed - the current dependency adds unnecessary weight and reduces flexibility.

> I was very fascinated by the use of Iterators and Generators in tolerant parsers. How can these functionalities be used in the LS, what changes would be needed, where do you see the best potential improvement?

Nothing immediately comes to mind, but it's a good question, and I'll think through some potential use cases. One learning from this work was to be *really* careful with generators in PHP - I ran some benchmarks, and found that they were 3-5x slower (and ~30x slower under xdebug) vs. instantiating and iterating through a comparable array, and many of the perf. improvements on the Node API side were due to removing the dependency on generators.

> hovers with (pretty-printed) fully qualified names (instead of local names)?

Full pretty printing (including adjusting whitespace) might take a little longer, but replacing qualified names w/ fully qualified names would be simple (already added a text edit api)
https://github.com/Microsoft/tolerant-php-parser/pull/85

> completions?

Let me look into this - my gut feel is that the logic itself is simple enough, but we may want to revisit some of the ways nodes are represented by the parser, specifically w.r.t. name tokens (e.g. may want to wrap them in nodes so that parent attributes are more easily accessible)

> yield support?

Hopefully next week - new grammatical constructs tend to be simple enough to add (e.g. see [return statements](https://github.com/Microsoft/tolerant-php-parser/commit/8d019cb731d6e5492eedf044c895124f5ab28089)). The hardest part about yield is that it's an expression, so precedence is a concern.

**Comment by felixfbecker** [comment]
Re: Caching
Thanks for the clarification, gotcha. Makes total sense to cache these resolutions.

Re: Logging
I would suggest to change the current logging to use the PSR3 logging interfaces. There will always be a need for simple logging and we can use it for "simple tracing" like logging the method calls for now and do OpenTracing later.

Re: Iterators
Interesting, wasn't aware of that. I wonder if it is improved in latest/upcoming PHP versions. Does that also hold true for returning an Iterator object manually?
I don't think you can compare an Iterator-based iteration directly to an array-based iteration of the same lenght, because the Iterator benefit comes from being able to "chaining" iterators and being able to cancel them. With arrays, every step is a new iterations, with Iterators, it's only a single iteration. And when traversing the AST to find a definition for example, we should be able to abort the iteration as soon as the node is found (which is possible with Iterators). And for searching symbols/references, we can stream results as soon as they are found. I also like the built-in support for recursive iterators, these sound like a great API for AST traversal.

Re: Index
Would love to hear your thoughts, write me on Gitter

I think the only major things that need to be done to get this merged are
- Removing the dual parser support
- Making Logging compatible with PSR3
- Completion
- yield support
- Merge conflicts ;)

File: validation/frameworks/_cases/WithReturnTypehints.php.expected.json [hunk 16]
```diff
@@ -0,0 +1,102 @@
+{
+    "references": {
+        "Fixtures\\Prophecy\\EmptyClass": [
+            "\/Users\/roblou\/code\/php-language-server\/tests\/Validation\/..\/..\/validation\/frameworks\/_cases\/WithReturnTypehints.php"
```
Comment (felixfbecker) [inline validation/frameworks/_cases/WithReturnTypehints.php.expected.json]: I assume this was generated from PHP's `json_encode`, can we use `JSON_UNESCAPED_SLASHES`?
This also should not include an absolute path

Comment (roblourens) [inline validation/frameworks/_cases/WithReturnTypehints.php.expected.json]: Thanks for the tip, and yes it should definitely not be an absolute path.

**Comment by roblourens** [comment]
For anyone who doesn't know, I'm taking over ownership of the PHP parser and the task of landing this PR. There's a lot of work to do still but I'm working through all the TODOs above and will get to all the comments eventually. The main thing I'm working towards right now is stabilizing the changes that were made to the parser for this PR, so I can merge them into the parser's master. They have diverged somewhat - https://github.com/Microsoft/tolerant-php-parser/compare/master...mousetraps:lang-server. php-language-server with the new parser shows some differences in completions and diagnostics which might reflect parser issues.

**Comment by felixfbecker** [comment]
Great to hear @roblourens, if there is anything I can help with let me know (here or on Gitter)

File: src/TolerantDefinitionResolver.php (hunk 1 above)
Comment (roblourens) [inline src/TolerantDefinitionResolver.php]: Looks like this has been replaced.

File: src/TolerantDefinitionResolver.php (hunk 2 above)
Comment (roblourens) [inline src/TolerantDefinitionResolver.php]: I think that isn't expected to be handled here. Finding the type of the param is done elsewhere.

File: src/TolerantDefinitionResolver.php (hunk 3 above)
Comment (roblourens) [inline src/TolerantDefinitionResolver.php]: Can $tag be null? I don't see that checked elsewhere.

Comment (felixfbecker) [inline src/TolerantDefinitionResolver.php]: It can't

File: src/TolerantDefinitionResolver.php (hunk 4 above)
Comment (roblourens) [inline src/TolerantDefinitionResolver.php]: That might be an interesting optimization to make later, if I can collect data on which structures are used most often.

File: src/TolerantDefinitionResolver.php (hunk 6 above)
Comment (roblourens) [inline src/TolerantDefinitionResolver.php]: This does appear to be missing...

Comment (roblourens) [inline src/TolerantDefinitionResolver.php]: Also missing from DefinitionResolver.php if I'm not mistaken.

File: src/TolerantDefinitionResolver.php (hunk 7 above)
Comment (roblourens) [inline src/TolerantDefinitionResolver.php]: Because [1,2,3] has integer keys by default

File: src/PhpDocument.php (hunk 8 above)
Comment (roblourens) [inline src/PhpDocument.php]: From what I understand, this is actually more performant because PHP will know that it's the global `is_array`.

File: src/TolerantDefinitionResolver.php (hunk 9 above)
Comment (roblourens) [inline src/TolerantDefinitionResolver.php]: I think, that there should be a nicer way to get the base class of a class declaration?

File: src/TolerantDefinitionResolver.php (hunk 7 above)
Comment (felixfbecker) [inline src/TolerantDefinitionResolver.php]: Exactly.

File: src/TolerantDefinitionResolver.php (hunk 10 above)
Comment (roblourens) [inline src/TolerantDefinitionResolver.php]: It looks like `'Hello', 'World'` is not a binary expression, but `echo` can just take multiple comma-delimited statements. But I can't do `$x = 'Hello', 'World'` for example.

File: src/TolerantDefinitionResolver.php (hunk 11 above)
Comment (roblourens) [inline src/TolerantDefinitionResolver.php]: This is handling binary expressions, e.g. `1+2`, so I don't think it's the right place for that.

File: src/TolerantDefinitionResolver.php (hunk 13 above)
Comment (roblourens) [inline src/TolerantDefinitionResolver.php]: Has been fixed

**Comment by roblourens** [comment]
Status update: I think the language server using the new parser is generally at parity with, or better than, what's currently in master. There are things that could be fixed or improved, but I want to move forward by doing just the things that absolutely need to be done to get this PR merged into master. Then we can publish a preview release, get it in front of people to test, and iterate from there.

Here's my list of things I'm working on right now, and when this list is complete, I'll feel comfortable merging this:
- [ ] Fix diagnostics tests
- [ ] Finish removing original DefinitionResolver and parser, and all references and type annotations, and supporting code like FqnUtilities. Rename TolerantDefinitionResolver to DefinitionResolver
- [ ] Do a sanity pass for comments on new code and formatting
- [ ] Remove LoggedDefResolver
- [ ] Handle merge conflicts

**Comment by roblourens** [comment]
I wonder whether we should keep the "Tolerant" alias everywhere in code, or get rid of it now that we don't need to distinguish between the two parsers and their different types? It would also make the diff easier to review if I remove it. Any opinions?

**Comment by jens1o** [comment]
I would like to remove it, because it just overpowers the code which worries user, who want to make a contibution, even more.

**Comment by felixfbecker** [comment]
I'm fine with removing it

**Comment by roblourens** [comment]
Here it is: a vsix built on this PR! I would really appreciate it if anyone can download and install this (change the .txt extension to .vsix) and spend some time using it. Like I said above, there are still some issues, but it should be at parity with the existing version of the extension. If you notice any issues, please try it with the existing extension to check whether it's a regression.

[php-intellisense-1.2.2.txt](https://github.com/felixfbecker/php-language-server/files/1030600/php-intellisense-1.2.2.txt)

On the PR itself, I still have to fix some formatting issues, but nothing major.

**Comment by jens1o** [comment]
It would be a pleasure to use this. I definitly install this.  ❤️

**Comment by jens1o** [comment]
It looks like the tolerant language server has problems with this construct:
image
I think this is valid php.

Code:
```php
 public static function getUserByLogin(string $userName, string $password, ?string $app = null): ?SmashcastUser {
//....
}
```

**Comment by jens1o** [comment]
It looks like inline variable overwrites aren't respected:
image
(I'd like to overwrite the variable after checking it is not null, because the function is based on nullable return types. This wasn't supported by the lsp at all.)

**Comment by GiacoCorsiglia** [comment]
First let me express my great appreciation for the work put into this extension and into this new version!

I believe I have discovered 2 regressions.

Uses of `include`, `require`, `include_once`, or `require_once` in expressions are incorrectly marked as errors:
```php
include 'foo.php';          // No error
include('foo.php');         // No error
if(include 'foo.php'){}     // No error
$bar = include 'foo.php';   // Error
$bar = (include 'foo.php'); // No error
@include 'foo.php';         // Error
@(include 'foo.php');       // No error
@include('foo.php');        // Error
!include 'foo.php';         // Error
```

Using the `static` keyword in `new static` without parentheses is also incorrectly marked as an error:
```php
class Foo {
  public function bar() {
    new Foo;      // No error
    new self;     // No error
    new static(); // No error
    new static;   // Error
  }
}
```

**Comment by jens1o** [comment]
```
[Error - 8:42:20 PM] Request textDocument/completion failed.
  Message: Error: Call to undefined method Microsoft\PhpParser\MissingToken::isFullyQualifiedName() in C:\Users\Jens\.vscode\extensions\felixfbecker.php-intellisense-1.2.2\vendor\felixfbecker\language-server\src\CompletionProvider.php:282
Stack trace:
#0 C:\Users\Jens\.vscode\extensions\felixfbecker.php-intellisense-1.2.2\vendor\felixfbecker\language-server\src\Server\TextDocument.php(346): LanguageServer\CompletionProvider->provideCompletion(Object(LanguageServer\PhpDocument), Object(LanguageServer\Protocol\Position))
#1 [internal function]: LanguageServer\Server\TextDocument->LanguageServer\Server\{closure}()
#2 C:\Users\Jens\.vscode\extensions\felixfbecker.php-intellisense-1.2.2\vendor\sabre\event\lib\coroutine.php(70): Generator->send(Object(LanguageServer\PhpDocument))
#3 C:\Users\Jens\.vscode\extensions\felixfbecker.php-intellisense-1.2.2\vendor\sabre\event\lib\Promise.php(242): Sabre\Event\{closure}(Object(LanguageServer\PhpDocument))
#4 C:\Users\Jens\.vscode\extensions\felixfbecker.php-intellisense-1.2.2\vendor\sabre\event\lib\Loop\Loop.php(261): Sabre\Event\Promise->Sabre\Event\{closure}()
#5 C:\Users\Jens\.vscode\extensions\felixfbecker.php-intellisense-1.2.2\vendor\sabre\event\lib\Loop\Loop.php(215): Sabre\Event\Loop\Loop->runNextTicks()
#6 C:\Users\Jens\.vscode\extensions\felixfbecker.php-intellisense-1.2.2\vendor\sabre\event\lib\Loop\Loop.php(194): Sabre\Event\Loop\Loop->tick(true)
#7 C:\Users\Jens\.vscode\extensions\felixfbecker.php-intellisense-1.2.2\vendor\sabre\event\lib\Loop\functions.php(122): Sabre\Event\Loop\Loop->run()
#8 C:\Users\Jens\.vscode\extensions\felixfbecker.php-intellisense-1.2.2\vendor\felixfbecker\language-server\bin\php-language-server.php(50): Sabre\Event\Loop\run()
#9 {main}
  Code: -32603 
```

This happens when I do the following:
1. Type `new`: 
image and wait for the underlining.
2. Directly type WITHOUT a space.(The first letter after the `new` expression must be alphanumeric.)
3. See that error.

**Comment by jens1o** [comment]
Feature request:
image
I would like to get notified that I'm breaking out of restrictions. I'm not allowed to return `false`, maybe you can implement that?

But I love it!

**Comment by jens1o** [comment]
It looks like the parser is not able to parse the source of a method when it is called directly after a method:

image
image
The parser thinks that the type `getStreamDetails` returns mixed, but in fact it is `SmashcastStreamDetails`

Project: https://github.com/jens1o/smashcast-api-php/

File:
```php
<?php
$start = microtime(true);
require_once './vendor/autoload.php';

use jens1o\smashcast\SmashcastApi;
use jens1o\smashcast\channel\SmashcastChannel;
use jens1o\smashcast\media\live\SmashcastLiveMedia;
use jens1o\smashcast\token\SmashcastAuthToken;
use jens1o\smashcast\user\SmashcastUser;
use jens1o\smashcast\user\oauth\SmashcastUserOauthList;
use jens1o\smashcast\util\{RequestUtil, LogoSize};
use jens1o\smashcast\oauth\SmashcastOauthHandler;
use jens1o\util\HttpMethod;

// https://api.smashcast.tv/media/live/Hitakashi-Test-Ban.json

// SmashcastApi::setAppName('OAuthTestJens');
// $user = SmashcastUser::getUserByLogin('jens1o', PASSWORD);
// SmashcastApi::setUserAuthToken($user->getAuthToken());

$liveMedia = new SmashcastLiveMedia('jens1o');

$stream = $liveMedia->getStreamDetails(); // mixed

var_dump($liveMedia->getStreamDetails()->getHeight()); // don't get hover for `getHeight()`
```

`getStreamDetails` exactly says what it is returning: 
image

So I don't understand why it is parsed as mixed.

**Comment by jens1o** [comment]
The language server has problems with parsing a new created `lumen` project.

Log:
```
[Info  - 2:25:03 PM] 3273 files total
[Info  - 2:25:04 PM] Indexing project for definitions and static references
Parsing file:///c:/nginx/html/projects/test-api/app/Console/Kernel.php
Parsing file:///c:/nginx/html/projects/test-api/app/Events/Event.php
Parsing file:///c:/nginx/html/projects/test-api/app/Events/ExampleEvent.php
Parsing file:///c:/nginx/html/projects/test-api/app/Exceptions/Handler.php
Parsing file:///c:/nginx/html/projects/test-api/app/Http/Controllers/Controller.php
Parsing file:///c:/nginx/html/projects/test-api/app/Http/Controllers/ExampleController.php
Parsing file:///c:/nginx/html/projects/test-api/app/Http/Middleware/Authenticate.php
Parsing file:///c:/nginx/html/projects/test-api/app/Http/Middleware/ExampleMiddleware.php
Parsing file:///c:/nginx/html/projects/test-api/app/Jobs/ExampleJob.php
Parsing file:///c:/nginx/html/projects/test-api/app/Jobs/Job.php
Parsing file:///c:/nginx/html/projects/test-api/app/Listeners/ExampleListener.php
Parsing file:///c:/nginx/html/projects/test-api/app/Providers/AppServiceProvider.php
Parsing file:///c:/nginx/html/projects/test-api/app/Providers/AuthServiceProvider.php
Parsing file:///c:/nginx/html/projects/test-api/app/Providers/EventServiceProvider.php
Parsing file:///c:/nginx/html/projects/test-api/app/User.php
Parsing file:///c:/nginx/html/projects/test-api/bootstrap/app.php
Parsing file:///c:/nginx/html/projects/test-api/database/factories/ModelFactory.php
Parsing file:///c:/nginx/html/projects/test-api/database/seeds/DatabaseSeeder.php
Parsing file:///c:/nginx/html/projects/test-api/public/index.php
Parsing file:///c:/nginx/html/projects/test-api/routes/web.php
Parsing file:///c:/nginx/html/projects/test-api/tests/ExampleTest.php
Parsing file:///c:/nginx/html/projects/test-api/tests/TestCase.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/autoload.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/composer/autoload_classmap.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/composer/autoload_files.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/composer/autoload_namespaces.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/composer/autoload_psr4.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/composer/autoload_real.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/composer/autoload_static.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/composer/ClassLoader.php
[Info  - 2:25:04 PM] Indexing project for dynamic references
Parsing file:///c:/nginx/html/projects/test-api/app/Console/Kernel.php
Parsing file:///c:/nginx/html/projects/test-api/app/Events/Event.php
Parsing file:///c:/nginx/html/projects/test-api/app/Events/ExampleEvent.php
Parsing file:///c:/nginx/html/projects/test-api/app/Exceptions/Handler.php
Parsing file:///c:/nginx/html/projects/test-api/app/Http/Controllers/Controller.php
Parsing file:///c:/nginx/html/projects/test-api/app/Http/Controllers/ExampleController.php
Parsing file:///c:/nginx/html/projects/test-api/app/Http/Middleware/Authenticate.php
Parsing file:///c:/nginx/html/projects/test-api/app/Http/Middleware/ExampleMiddleware.php
Parsing file:///c:/nginx/html/projects/test-api/app/Jobs/ExampleJob.php
Parsing file:///c:/nginx/html/projects/test-api/app/Jobs/Job.php
Parsing file:///c:/nginx/html/projects/test-api/app/Listeners/ExampleListener.php
Parsing file:///c:/nginx/html/projects/test-api/app/Providers/AppServiceProvider.php
Parsing file:///c:/nginx/html/projects/test-api/app/Providers/AuthServiceProvider.php
Parsing file:///c:/nginx/html/projects/test-api/app/Providers/EventServiceProvider.php
Parsing file:///c:/nginx/html/projects/test-api/app/User.php
Parsing file:///c:/nginx/html/projects/test-api/bootstrap/app.php
Parsing file:///c:/nginx/html/projects/test-api/database/factories/ModelFactory.php
Parsing file:///c:/nginx/html/projects/test-api/database/seeds/DatabaseSeeder.php
Parsing file:///c:/nginx/html/projects/test-api/public/index.php
Parsing file:///c:/nginx/html/projects/test-api/routes/web.php
Parsing file:///c:/nginx/html/projects/test-api/tests/ExampleTest.php
Parsing file:///c:/nginx/html/projects/test-api/tests/TestCase.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/autoload.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/composer/autoload_classmap.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/composer/autoload_files.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/composer/autoload_namespaces.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/composer/autoload_psr4.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/composer/autoload_real.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/composer/autoload_static.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/composer/ClassLoader.php
[Info  - 2:25:05 PM] 68 Packages
[Info  - 2:25:05 PM] Restored doctrine/inflector:1.1.0 from cache
[Info  - 2:25:06 PM] Restored doctrine/instantiator:1.0.5 from cache
[Info  - 2:25:06 PM] Restored fzaninotto/faker:1.6.0 from cache
[Info  - 2:25:06 PM] Restored hamcrest/hamcrest-php:1.2.2 from cache
[Info  - 2:25:06 PM] Indexing illuminate/auth:5.4.19 for definitions and static references
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/auth/Access/AuthorizationException.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/auth/Access/Gate.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/auth/Access/HandlesAuthorization.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/auth/Access/Response.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/auth/Authenticatable.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/auth/AuthenticationException.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/auth/AuthManager.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/auth/AuthServiceProvider.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/auth/Console/ClearResetsCommand.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/auth/Console/MakeAuthCommand.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/auth/CreatesUserProviders.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/auth/DatabaseUserProvider.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/auth/EloquentUserProvider.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/auth/Events/Attempting.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/auth/Events/Authenticated.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/auth/Events/Failed.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/auth/Events/Lockout.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/auth/Events/Login.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/auth/Events/Logout.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/auth/Events/Registered.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/auth/GenericUser.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/auth/GuardHelpers.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/auth/Middleware/Authenticate.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/auth/Middleware/AuthenticateWithBasicAuth.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/auth/Middleware/Authorize.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/auth/Notifications/ResetPassword.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/auth/Passwords/CanResetPassword.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/auth/Passwords/DatabaseTokenRepository.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/auth/Passwords/PasswordBroker.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/auth/Passwords/PasswordBrokerManager.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/auth/Passwords/PasswordResetServiceProvider.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/auth/Passwords/TokenRepositoryInterface.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/auth/Recaller.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/auth/RequestGuard.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/auth/SessionGuard.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/auth/TokenGuard.php
[Info  - 2:25:07 PM] Indexing illuminate/auth:5.4.19 for dynamic references
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/auth/Access/AuthorizationException.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/auth/Access/Gate.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/auth/Access/HandlesAuthorization.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/auth/Access/Response.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/auth/Authenticatable.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/auth/AuthenticationException.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/auth/AuthManager.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/auth/AuthServiceProvider.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/auth/Console/ClearResetsCommand.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/auth/Console/MakeAuthCommand.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/auth/CreatesUserProviders.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/auth/DatabaseUserProvider.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/auth/EloquentUserProvider.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/auth/Events/Attempting.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/auth/Events/Authenticated.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/auth/Events/Failed.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/auth/Events/Lockout.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/auth/Events/Login.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/auth/Events/Logout.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/auth/Events/Registered.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/auth/GenericUser.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/auth/GuardHelpers.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/auth/Middleware/Authenticate.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/auth/Middleware/AuthenticateWithBasicAuth.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/auth/Middleware/Authorize.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/auth/Notifications/ResetPassword.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/auth/Passwords/CanResetPassword.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/auth/Passwords/DatabaseTokenRepository.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/auth/Passwords/PasswordBroker.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/auth/Passwords/PasswordBrokerManager.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/auth/Passwords/PasswordResetServiceProvider.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/auth/Passwords/TokenRepositoryInterface.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/auth/Recaller.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/auth/RequestGuard.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/auth/SessionGuard.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/auth/TokenGuard.php
[Info  - 2:25:07 PM] Storing illuminate/auth:5.4.19 in cache
[Info  - 2:25:07 PM] Indexing illuminate/broadcasting:5.4.19 for definitions and static references
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/broadcasting/BroadcastController.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/broadcasting/Broadcasters/Broadcaster.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/broadcasting/Broadcasters/LogBroadcaster.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/broadcasting/Broadcasters/NullBroadcaster.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/broadcasting/Broadcasters/PusherBroadcaster.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/broadcasting/Broadcasters/RedisBroadcaster.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/broadcasting/BroadcastEvent.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/broadcasting/BroadcastException.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/broadcasting/BroadcastManager.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/broadcasting/BroadcastServiceProvider.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/broadcasting/Channel.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/broadcasting/InteractsWithSockets.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/broadcasting/PendingBroadcast.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/broadcasting/PresenceChannel.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/broadcasting/PrivateChannel.php
[Info  - 2:25:07 PM] Indexing illuminate/broadcasting:5.4.19 for dynamic references
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/broadcasting/BroadcastController.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/broadcasting/Broadcasters/Broadcaster.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/broadcasting/Broadcasters/LogBroadcaster.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/broadcasting/Broadcasters/NullBroadcaster.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/broadcasting/Broadcasters/PusherBroadcaster.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/broadcasting/Broadcasters/RedisBroadcaster.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/broadcasting/BroadcastEvent.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/broadcasting/BroadcastException.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/broadcasting/BroadcastManager.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/broadcasting/BroadcastServiceProvider.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/broadcasting/Channel.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/broadcasting/InteractsWithSockets.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/broadcasting/PendingBroadcast.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/broadcasting/PresenceChannel.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/broadcasting/PrivateChannel.php
[Info  - 2:25:08 PM] Storing illuminate/broadcasting:5.4.19 in cache
[Info  - 2:25:08 PM] Indexing illuminate/bus:5.4.19 for definitions and static references
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/bus/BusServiceProvider.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/bus/Dispatcher.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/bus/Queueable.php
[Info  - 2:25:08 PM] Indexing illuminate/bus:5.4.19 for dynamic references
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/bus/BusServiceProvider.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/bus/Dispatcher.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/bus/Queueable.php
[Info  - 2:25:08 PM] Storing illuminate/bus:5.4.19 in cache
[Info  - 2:25:08 PM] Indexing illuminate/cache:5.4.19 for definitions and static references
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/cache/ApcStore.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/cache/ApcWrapper.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/cache/ArrayStore.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/cache/CacheManager.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/cache/CacheServiceProvider.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/cache/Console/CacheTableCommand.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/cache/Console/ClearCommand.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/cache/Console/ForgetCommand.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/cache/DatabaseStore.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/cache/Events/CacheEvent.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/cache/Events/CacheHit.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/cache/Events/CacheMissed.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/cache/Events/KeyForgotten.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/cache/Events/KeyWritten.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/cache/FileStore.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/cache/MemcachedConnector.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/cache/MemcachedStore.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/cache/NullStore.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/cache/RateLimiter.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/cache/RedisStore.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/cache/RedisTaggedCache.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/cache/Repository.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/cache/RetrievesMultipleKeys.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/cache/TaggableStore.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/cache/TaggedCache.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/cache/TagSet.php
[Info  - 2:25:08 PM] Indexing illuminate/cache:5.4.19 for dynamic references
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/cache/ApcStore.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/cache/ApcWrapper.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/cache/ArrayStore.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/cache/CacheManager.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/cache/CacheServiceProvider.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/cache/Console/CacheTableCommand.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/cache/Console/ClearCommand.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/cache/Console/ForgetCommand.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/cache/DatabaseStore.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/cache/Events/CacheEvent.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/cache/Events/CacheHit.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/cache/Events/CacheMissed.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/cache/Events/KeyForgotten.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/cache/Events/KeyWritten.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/cache/FileStore.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/cache/MemcachedConnector.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/cache/MemcachedStore.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/cache/NullStore.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/cache/RateLimiter.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/cache/RedisStore.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/cache/RedisTaggedCache.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/cache/Repository.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/cache/RetrievesMultipleKeys.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/cache/TaggableStore.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/cache/TaggedCache.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/cache/TagSet.php
[Info  - 2:25:09 PM] Storing illuminate/cache:5.4.19 in cache
[Info  - 2:25:09 PM] Indexing illuminate/config:5.4.19 for definitions and static references
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/config/Repository.php
[Info  - 2:25:09 PM] Indexing illuminate/config:5.4.19 for dynamic references
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/config/Repository.php
[Info  - 2:25:09 PM] Storing illuminate/config:5.4.19 in cache
[Info  - 2:25:09 PM] Indexing illuminate/console:5.4.19 for definitions and static references
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/console/Application.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/console/Command.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/console/ConfirmableTrait.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/console/DetectsApplicationNamespace.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/console/Events/ArtisanStarting.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/console/GeneratorCommand.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/console/OutputStyle.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/console/Parser.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/console/Scheduling/CacheMutex.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/console/Scheduling/CallbackEvent.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/console/Scheduling/CommandBuilder.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/console/Scheduling/Event.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/console/Scheduling/ManagesFrequencies.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/console/Scheduling/Mutex.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/console/Scheduling/Schedule.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/console/Scheduling/ScheduleFinishCommand.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/console/Scheduling/ScheduleRunCommand.php
[Info  - 2:25:09 PM] Indexing illuminate/console:5.4.19 for dynamic references
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/console/Application.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/console/Command.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/console/ConfirmableTrait.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/console/DetectsApplicationNamespace.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/console/Events/ArtisanStarting.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/console/GeneratorCommand.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/console/OutputStyle.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/console/Parser.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/console/Scheduling/CacheMutex.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/console/Scheduling/CallbackEvent.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/console/Scheduling/CommandBuilder.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/console/Scheduling/Event.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/console/Scheduling/ManagesFrequencies.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/console/Scheduling/Mutex.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/console/Scheduling/Schedule.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/console/Scheduling/ScheduleFinishCommand.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/console/Scheduling/ScheduleRunCommand.php
[Info  - 2:25:10 PM] Storing illuminate/console:5.4.19 in cache
[Info  - 2:25:10 PM] Indexing illuminate/container:5.4.19 for definitions and static references
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/container/BoundMethod.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/container/Container.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/container/ContextualBindingBuilder.php
[Info  - 2:25:10 PM] Indexing illuminate/container:5.4.19 for dynamic references
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/container/BoundMethod.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/container/Container.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/container/ContextualBindingBuilder.php
[Info  - 2:25:10 PM] Storing illuminate/container:5.4.19 in cache
[Info  - 2:25:10 PM] Indexing illuminate/contracts:5.4.19 for definitions and static references
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/contracts/Auth/Access/Authorizable.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/contracts/Auth/Access/Gate.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/contracts/Auth/Authenticatable.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/contracts/Auth/CanResetPassword.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/contracts/Auth/Factory.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/contracts/Auth/Guard.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/contracts/Auth/PasswordBroker.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/contracts/Auth/PasswordBrokerFactory.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/contracts/Auth/StatefulGuard.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/contracts/Auth/SupportsBasicAuth.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/contracts/Auth/UserProvider.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/contracts/Broadcasting/Broadcaster.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/contracts/Broadcasting/Factory.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/contracts/Broadcasting/ShouldBroadcast.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/contracts/Broadcasting/ShouldBroadcastNow.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/contracts/Bus/Dispatcher.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/contracts/Bus/QueueingDispatcher.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/contracts/Cache/Factory.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/contracts/Cache/Repository.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/contracts/Cache/Store.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/contracts/Config/Repository.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/contracts/Console/Application.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/contracts/Console/Kernel.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/contracts/Container/BindingResolutionException.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/contracts/Container/Container.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/contracts/Container/ContextualBindingBuilder.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/contracts/Cookie/Factory.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/contracts/Cookie/QueueingFactory.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/contracts/Database/ModelIdentifier.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/contracts/Debug/ExceptionHandler.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/contracts/Encryption/DecryptException.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/contracts/Encryption/Encrypter.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/contracts/Encryption/EncryptException.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/contracts/Events/Dispatcher.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/contracts/Filesystem/Cloud.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/contracts/Filesystem/Factory.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/contracts/Filesystem/FileNotFoundException.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/contracts/Filesystem/Filesystem.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/contracts/Foundation/Application.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/contracts/Hashing/Hasher.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/contracts/Http/Kernel.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/contracts/Logging/Log.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/contracts/Mail/Mailable.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/contracts/Mail/Mailer.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/contracts/Mail/MailQueue.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/contracts/Notifications/Dispatcher.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/contracts/Notifications/Factory.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/contracts/Pagination/LengthAwarePaginator.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/contracts/Pagination/Paginator.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/contracts/Pipeline/Hub.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/contracts/Pipeline/Pipeline.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/contracts/Queue/EntityNotFoundException.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/contracts/Queue/EntityResolver.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/contracts/Queue/Factory.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/contracts/Queue/Job.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/contracts/Queue/Monitor.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/contracts/Queue/Queue.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/contracts/Queue/QueueableCollection.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/contracts/Queue/QueueableEntity.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/contracts/Queue/ShouldQueue.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/contracts/Redis/Factory.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/contracts/Routing/BindingRegistrar.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/contracts/Routing/Registrar.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/contracts/Routing/ResponseFactory.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/contracts/Routing/UrlGenerator.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/contracts/Routing/UrlRoutable.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/contracts/Session/Session.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/contracts/Support/Arrayable.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/contracts/Support/Htmlable.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/contracts/Support/Jsonable.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/contracts/Support/MessageBag.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/contracts/Support/MessageProvider.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/contracts/Support/Renderable.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/contracts/Translation/Translator.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/contracts/Validation/Factory.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/contracts/Validation/ValidatesWhenResolved.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/contracts/Validation/Validator.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/contracts/View/Factory.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/contracts/View/View.php
[Info  - 2:25:11 PM] Indexing illuminate/contracts:5.4.19 for dynamic references
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/contracts/Auth/Access/Authorizable.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/contracts/Auth/Access/Gate.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/contracts/Auth/Authenticatable.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/contracts/Auth/CanResetPassword.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/contracts/Auth/Factory.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/contracts/Auth/Guard.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/contracts/Auth/PasswordBroker.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/contracts/Auth/PasswordBrokerFactory.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/contracts/Auth/StatefulGuard.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/contracts/Auth/SupportsBasicAuth.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/contracts/Auth/UserProvider.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/contracts/Broadcasting/Broadcaster.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/contracts/Broadcasting/Factory.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/contracts/Broadcasting/ShouldBroadcast.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/contracts/Broadcasting/ShouldBroadcastNow.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/contracts/Bus/Dispatcher.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/contracts/Bus/QueueingDispatcher.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/contracts/Cache/Factory.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/contracts/Cache/Repository.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/contracts/Cache/Store.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/contracts/Config/Repository.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/contracts/Console/Application.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/contracts/Console/Kernel.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/contracts/Container/BindingResolutionException.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/contracts/Container/Container.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/contracts/Container/ContextualBindingBuilder.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/contracts/Cookie/Factory.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/contracts/Cookie/QueueingFactory.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/contracts/Database/ModelIdentifier.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/contracts/Debug/ExceptionHandler.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/contracts/Encryption/DecryptException.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/contracts/Encryption/Encrypter.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/contracts/Encryption/EncryptException.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/contracts/Events/Dispatcher.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/contracts/Filesystem/Cloud.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/contracts/Filesystem/Factory.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/contracts/Filesystem/FileNotFoundException.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/contracts/Filesystem/Filesystem.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/contracts/Foundation/Application.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/contracts/Hashing/Hasher.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/contracts/Http/Kernel.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/contracts/Logging/Log.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/contracts/Mail/Mailable.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/contracts/Mail/Mailer.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/contracts/Mail/MailQueue.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/contracts/Notifications/Dispatcher.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/contracts/Notifications/Factory.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/contracts/Pagination/LengthAwarePaginator.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/contracts/Pagination/Paginator.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/contracts/Pipeline/Hub.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/contracts/Pipeline/Pipeline.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/contracts/Queue/EntityNotFoundException.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/contracts/Queue/EntityResolver.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/contracts/Queue/Factory.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/contracts/Queue/Job.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/contracts/Queue/Monitor.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/contracts/Queue/Queue.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/contracts/Queue/QueueableCollection.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/contracts/Queue/QueueableEntity.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/contracts/Queue/ShouldQueue.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/contracts/Redis/Factory.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/contracts/Routing/BindingRegistrar.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/contracts/Routing/Registrar.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/contracts/Routing/ResponseFactory.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/contracts/Routing/UrlGenerator.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/contracts/Routing/UrlRoutable.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/contracts/Session/Session.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/contracts/Support/Arrayable.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/contracts/Support/Htmlable.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/contracts/Support/Jsonable.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/contracts/Support/MessageBag.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/contracts/Support/MessageProvider.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/contracts/Support/Renderable.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/contracts/Translation/Translator.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/contracts/Validation/Factory.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/contracts/Validation/ValidatesWhenResolved.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/contracts/Validation/Validator.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/contracts/View/Factory.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/contracts/View/View.php
[Info  - 2:25:11 PM] Storing illuminate/contracts:5.4.19 in cache
[Info  - 2:25:11 PM] Indexing illuminate/database:5.4.19 for definitions and static references
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/database/Capsule/Manager.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/database/Concerns/BuildsQueries.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/database/Concerns/ManagesTransactions.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/database/Connection.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/database/ConnectionInterface.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/database/ConnectionResolver.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/database/ConnectionResolverInterface.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/database/Connectors/ConnectionFactory.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/database/Connectors/Connector.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/database/Connectors/ConnectorInterface.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/database/Connectors/MySqlConnector.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/database/Connectors/PostgresConnector.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/database/Connectors/SQLiteConnector.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/database/Connectors/SqlServerConnector.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/database/Console/Migrations/BaseCommand.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/database/Console/Migrations/InstallCommand.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/database/Console/Migrations/MigrateCommand.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/database/Console/Migrations/MigrateMakeCommand.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/database/Console/Migrations/RefreshCommand.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/database/Console/Migrations/ResetCommand.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/database/Console/Migrations/RollbackCommand.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/database/Console/Migrations/StatusCommand.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/database/Console/Seeds/SeedCommand.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/database/Console/Seeds/SeederMakeCommand.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/database/DatabaseManager.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/database/DatabaseServiceProvider.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/database/DetectsDeadlocks.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/database/DetectsLostConnections.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/database/Eloquent/Builder.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/database/Eloquent/Collection.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/database/Eloquent/Concerns/GuardsAttributes.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/database/Eloquent/Concerns/HasAttributes.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/database/Eloquent/Concerns/HasEvents.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/database/Eloquent/Concerns/HasGlobalScopes.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/database/Eloquent/Concerns/HasRelationships.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/database/Eloquent/Concerns/HasTimestamps.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/database/Eloquent/Concerns/HidesAttributes.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/database/Eloquent/Concerns/QueriesRelationships.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/database/Eloquent/Factory.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/database/Eloquent/FactoryBuilder.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/database/Eloquent/JsonEncodingException.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/database/Eloquent/MassAssignmentException.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/database/Eloquent/Model.php
[Info  - 2:25:13 PM] Connection to server got closed. Server will restart.
[Info  - 2:25:17 PM] 3273 files total
[Info  - 2:25:17 PM] Indexing project for definitions and static references
Parsing file:///c:/nginx/html/projects/test-api/app/Console/Kernel.php
Parsing file:///c:/nginx/html/projects/test-api/app/Events/Event.php
Parsing file:///c:/nginx/html/projects/test-api/app/Events/ExampleEvent.php
Parsing file:///c:/nginx/html/projects/test-api/app/Exceptions/Handler.php
Parsing file:///c:/nginx/html/projects/test-api/app/Http/Controllers/Controller.php
Parsing file:///c:/nginx/html/projects/test-api/app/Http/Controllers/ExampleController.php
Parsing file:///c:/nginx/html/projects/test-api/app/Http/Middleware/Authenticate.php
Parsing file:///c:/nginx/html/projects/test-api/app/Http/Middleware/ExampleMiddleware.php
Parsing file:///c:/nginx/html/projects/test-api/app/Jobs/ExampleJob.php
Parsing file:///c:/nginx/html/projects/test-api/app/Jobs/Job.php
Parsing file:///c:/nginx/html/projects/test-api/app/Listeners/ExampleListener.php
Parsing file:///c:/nginx/html/projects/test-api/app/Providers/AppServiceProvider.php
Parsing file:///c:/nginx/html/projects/test-api/app/Providers/AuthServiceProvider.php
Parsing file:///c:/nginx/html/projects/test-api/app/Providers/EventServiceProvider.php
Parsing file:///c:/nginx/html/projects/test-api/app/User.php
Parsing file:///c:/nginx/html/projects/test-api/bootstrap/app.php
Parsing file:///c:/nginx/html/projects/test-api/database/factories/ModelFactory.php
Parsing file:///c:/nginx/html/projects/test-api/database/seeds/DatabaseSeeder.php
Parsing file:///c:/nginx/html/projects/test-api/public/index.php
Parsing file:///c:/nginx/html/projects/test-api/routes/web.php
Parsing file:///c:/nginx/html/projects/test-api/tests/ExampleTest.php
Parsing file:///c:/nginx/html/projects/test-api/tests/TestCase.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/autoload.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/composer/autoload_classmap.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/composer/autoload_files.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/composer/autoload_namespaces.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/composer/autoload_psr4.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/composer/autoload_real.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/composer/autoload_static.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/composer/ClassLoader.php
[Info  - 2:25:17 PM] Indexing project for dynamic references
Parsing file:///c:/nginx/html/projects/test-api/app/Console/Kernel.php
Parsing file:///c:/nginx/html/projects/test-api/app/Events/Event.php
Parsing file:///c:/nginx/html/projects/test-api/app/Events/ExampleEvent.php
Parsing file:///c:/nginx/html/projects/test-api/app/Exceptions/Handler.php
Parsing file:///c:/nginx/html/projects/test-api/app/Http/Controllers/Controller.php
Parsing file:///c:/nginx/html/projects/test-api/app/Http/Controllers/ExampleController.php
Parsing file:///c:/nginx/html/projects/test-api/app/Http/Middleware/Authenticate.php
Parsing file:///c:/nginx/html/projects/test-api/app/Http/Middleware/ExampleMiddleware.php
Parsing file:///c:/nginx/html/projects/test-api/app/Jobs/ExampleJob.php
Parsing file:///c:/nginx/html/projects/test-api/app/Jobs/Job.php
Parsing file:///c:/nginx/html/projects/test-api/app/Listeners/ExampleListener.php
Parsing file:///c:/nginx/html/projects/test-api/app/Providers/AppServiceProvider.php
Parsing file:///c:/nginx/html/projects/test-api/app/Providers/AuthServiceProvider.php
Parsing file:///c:/nginx/html/projects/test-api/app/Providers/EventServiceProvider.php
Parsing file:///c:/nginx/html/projects/test-api/app/User.php
Parsing file:///c:/nginx/html/projects/test-api/bootstrap/app.php
Parsing file:///c:/nginx/html/projects/test-api/database/factories/ModelFactory.php
Parsing file:///c:/nginx/html/projects/test-api/database/seeds/DatabaseSeeder.php
Parsing file:///c:/nginx/html/projects/test-api/public/index.php
Parsing file:///c:/nginx/html/projects/test-api/routes/web.php
Parsing file:///c:/nginx/html/projects/test-api/tests/ExampleTest.php
Parsing file:///c:/nginx/html/projects/test-api/tests/TestCase.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/autoload.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/composer/autoload_classmap.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/composer/autoload_files.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/composer/autoload_namespaces.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/composer/autoload_psr4.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/composer/autoload_real.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/composer/autoload_static.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/composer/ClassLoader.php
[Info  - 2:25:18 PM] 68 Packages
[Info  - 2:25:18 PM] Restored doctrine/inflector:1.1.0 from cache
[Info  - 2:25:18 PM] Restored doctrine/instantiator:1.0.5 from cache
[Info  - 2:25:18 PM] Restored fzaninotto/faker:1.6.0 from cache
[Info  - 2:25:18 PM] Restored hamcrest/hamcrest-php:1.2.2 from cache
[Info  - 2:25:18 PM] Restored illuminate/auth:5.4.19 from cache
[Info  - 2:25:18 PM] Restored illuminate/broadcasting:5.4.19 from cache
[Info  - 2:25:18 PM] Restored illuminate/bus:5.4.19 from cache
[Info  - 2:25:18 PM] Restored illuminate/cache:5.4.19 from cache
[Info  - 2:25:18 PM] Restored illuminate/config:5.4.19 from cache
[Info  - 2:25:18 PM] Restored illuminate/console:5.4.19 from cache
[Info  - 2:25:18 PM] Restored illuminate/container:5.4.19 from cache
[Info  - 2:25:18 PM] Restored illuminate/contracts:5.4.19 from cache
[Info  - 2:25:18 PM] Indexing illuminate/database:5.4.19 for definitions and static references
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/database/Capsule/Manager.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/database/Concerns/BuildsQueries.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/database/Concerns/ManagesTransactions.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/database/Connection.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/database/ConnectionInterface.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/database/ConnectionResolver.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/database/ConnectionResolverInterface.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/database/Connectors/ConnectionFactory.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/database/Connectors/Connector.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/database/Connectors/ConnectorInterface.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/database/Connectors/MySqlConnector.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/database/Connectors/PostgresConnector.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/database/Connectors/SQLiteConnector.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/database/Connectors/SqlServerConnector.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/database/Console/Migrations/BaseCommand.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/database/Console/Migrations/InstallCommand.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/database/Console/Migrations/MigrateCommand.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/database/Console/Migrations/MigrateMakeCommand.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/database/Console/Migrations/RefreshCommand.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/database/Console/Migrations/ResetCommand.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/database/Console/Migrations/RollbackCommand.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/database/Console/Migrations/StatusCommand.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/database/Console/Seeds/SeedCommand.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/database/Console/Seeds/SeederMakeCommand.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/database/DatabaseManager.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/database/DatabaseServiceProvider.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/database/DetectsDeadlocks.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/database/DetectsLostConnections.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/database/Eloquent/Builder.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/database/Eloquent/Collection.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/database/Eloquent/Concerns/GuardsAttributes.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/database/Eloquent/Concerns/HasAttributes.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/database/Eloquent/Concerns/HasEvents.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/database/Eloquent/Concerns/HasGlobalScopes.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/database/Eloquent/Concerns/HasRelationships.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/database/Eloquent/Concerns/HasTimestamps.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/database/Eloquent/Concerns/HidesAttributes.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/database/Eloquent/Concerns/QueriesRelationships.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/database/Eloquent/Factory.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/database/Eloquent/FactoryBuilder.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/database/Eloquent/JsonEncodingException.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/database/Eloquent/MassAssignmentException.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/database/Eloquent/Model.php
[Info  - 2:25:19 PM] Connection to server got closed. Server will restart.
[Info  - 2:25:22 PM] 3273 files total
[Info  - 2:25:22 PM] Indexing project for definitions and static references
Parsing file:///c:/nginx/html/projects/test-api/app/Console/Kernel.php
Parsing file:///c:/nginx/html/projects/test-api/app/Events/Event.php
Parsing file:///c:/nginx/html/projects/test-api/app/Events/ExampleEvent.php
Parsing file:///c:/nginx/html/projects/test-api/app/Exceptions/Handler.php
Parsing file:///c:/nginx/html/projects/test-api/app/Http/Controllers/Controller.php
Parsing file:///c:/nginx/html/projects/test-api/app/Http/Controllers/ExampleController.php
Parsing file:///c:/nginx/html/projects/test-api/app/Http/Middleware/Authenticate.php
Parsing file:///c:/nginx/html/projects/test-api/app/Http/Middleware/ExampleMiddleware.php
Parsing file:///c:/nginx/html/projects/test-api/app/Jobs/ExampleJob.php
Parsing file:///c:/nginx/html/projects/test-api/app/Jobs/Job.php
Parsing file:///c:/nginx/html/projects/test-api/app/Listeners/ExampleListener.php
Parsing file:///c:/nginx/html/projects/test-api/app/Providers/AppServiceProvider.php
Parsing file:///c:/nginx/html/projects/test-api/app/Providers/AuthServiceProvider.php
Parsing file:///c:/nginx/html/projects/test-api/app/Providers/EventServiceProvider.php
Parsing file:///c:/nginx/html/projects/test-api/app/User.php
Parsing file:///c:/nginx/html/projects/test-api/bootstrap/app.php
Parsing file:///c:/nginx/html/projects/test-api/database/factories/ModelFactory.php
Parsing file:///c:/nginx/html/projects/test-api/database/seeds/DatabaseSeeder.php
Parsing file:///c:/nginx/html/projects/test-api/public/index.php
Parsing file:///c:/nginx/html/projects/test-api/routes/web.php
Parsing file:///c:/nginx/html/projects/test-api/tests/ExampleTest.php
Parsing file:///c:/nginx/html/projects/test-api/tests/TestCase.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/autoload.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/composer/autoload_classmap.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/composer/autoload_files.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/composer/autoload_namespaces.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/composer/autoload_psr4.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/composer/autoload_real.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/composer/autoload_static.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/composer/ClassLoader.php
[Info  - 2:25:23 PM] Indexing project for dynamic references
Parsing file:///c:/nginx/html/projects/test-api/app/Console/Kernel.php
Parsing file:///c:/nginx/html/projects/test-api/app/Events/Event.php
Parsing file:///c:/nginx/html/projects/test-api/app/Events/ExampleEvent.php
Parsing file:///c:/nginx/html/projects/test-api/app/Exceptions/Handler.php
Parsing file:///c:/nginx/html/projects/test-api/app/Http/Controllers/Controller.php
Parsing file:///c:/nginx/html/projects/test-api/app/Http/Controllers/ExampleController.php
Parsing file:///c:/nginx/html/projects/test-api/app/Http/Middleware/Authenticate.php
Parsing file:///c:/nginx/html/projects/test-api/app/Http/Middleware/ExampleMiddleware.php
Parsing file:///c:/nginx/html/projects/test-api/app/Jobs/ExampleJob.php
Parsing file:///c:/nginx/html/projects/test-api/app/Jobs/Job.php
Parsing file:///c:/nginx/html/projects/test-api/app/Listeners/ExampleListener.php
Parsing file:///c:/nginx/html/projects/test-api/app/Providers/AppServiceProvider.php
Parsing file:///c:/nginx/html/projects/test-api/app/Providers/AuthServiceProvider.php
Parsing file:///c:/nginx/html/projects/test-api/app/Providers/EventServiceProvider.php
Parsing file:///c:/nginx/html/projects/test-api/app/User.php
Parsing file:///c:/nginx/html/projects/test-api/bootstrap/app.php
Parsing file:///c:/nginx/html/projects/test-api/database/factories/ModelFactory.php
Parsing file:///c:/nginx/html/projects/test-api/database/seeds/DatabaseSeeder.php
Parsing file:///c:/nginx/html/projects/test-api/public/index.php
Parsing file:///c:/nginx/html/projects/test-api/routes/web.php
Parsing file:///c:/nginx/html/projects/test-api/tests/ExampleTest.php
Parsing file:///c:/nginx/html/projects/test-api/tests/TestCase.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/autoload.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/composer/autoload_classmap.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/composer/autoload_files.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/composer/autoload_namespaces.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/composer/autoload_psr4.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/composer/autoload_real.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/composer/autoload_static.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/composer/ClassLoader.php
[Info  - 2:25:23 PM] 68 Packages
[Info  - 2:25:23 PM] Restored doctrine/inflector:1.1.0 from cache
[Info  - 2:25:23 PM] Restored doctrine/instantiator:1.0.5 from cache
[Info  - 2:25:23 PM] Restored fzaninotto/faker:1.6.0 from cache
[Info  - 2:25:24 PM] Restored hamcrest/hamcrest-php:1.2.2 from cache
[Info  - 2:25:24 PM] Restored illuminate/auth:5.4.19 from cache
[Info  - 2:25:24 PM] Restored illuminate/broadcasting:5.4.19 from cache
[Info  - 2:25:24 PM] Restored illuminate/bus:5.4.19 from cache
[Info  - 2:25:24 PM] Restored illuminate/cache:5.4.19 from cache
[Info  - 2:25:24 PM] Restored illuminate/config:5.4.19 from cache
[Info  - 2:25:24 PM] Restored illuminate/console:5.4.19 from cache
[Info  - 2:25:24 PM] Restored illuminate/container:5.4.19 from cache
[Info  - 2:25:24 PM] Restored illuminate/contracts:5.4.19 from cache
[Info  - 2:25:24 PM] Indexing illuminate/database:5.4.19 for definitions and static references
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/database/Capsule/Manager.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/database/Concerns/BuildsQueries.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/database/Concerns/ManagesTransactions.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/database/Connection.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/database/ConnectionInterface.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/database/ConnectionResolver.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/database/ConnectionResolverInterface.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/database/Connectors/ConnectionFactory.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/database/Connectors/Connector.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/database/Connectors/ConnectorInterface.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/database/Connectors/MySqlConnector.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/database/Connectors/PostgresConnector.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/database/Connectors/SQLiteConnector.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/database/Connectors/SqlServerConnector.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/database/Console/Migrations/BaseCommand.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/database/Console/Migrations/InstallCommand.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/database/Console/Migrations/MigrateCommand.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/database/Console/Migrations/MigrateMakeCommand.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/database/Console/Migrations/RefreshCommand.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/database/Console/Migrations/ResetCommand.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/database/Console/Migrations/RollbackCommand.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/database/Console/Migrations/StatusCommand.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/database/Console/Seeds/SeedCommand.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/database/Console/Seeds/SeederMakeCommand.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/database/DatabaseManager.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/database/DatabaseServiceProvider.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/database/DetectsDeadlocks.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/database/DetectsLostConnections.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/database/Eloquent/Builder.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/database/Eloquent/Collection.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/database/Eloquent/Concerns/GuardsAttributes.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/database/Eloquent/Concerns/HasAttributes.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/database/Eloquent/Concerns/HasEvents.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/database/Eloquent/Concerns/HasGlobalScopes.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/database/Eloquent/Concerns/HasRelationships.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/database/Eloquent/Concerns/HasTimestamps.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/database/Eloquent/Concerns/HidesAttributes.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/database/Eloquent/Concerns/QueriesRelationships.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/database/Eloquent/Factory.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/database/Eloquent/FactoryBuilder.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/database/Eloquent/JsonEncodingException.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/database/Eloquent/MassAssignmentException.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/database/Eloquent/Model.php
[Info  - 2:25:25 PM] Connection to server got closed. Server will restart.
[Info  - 2:25:28 PM] 3273 files total
[Info  - 2:25:28 PM] Indexing project for definitions and static references
Parsing file:///c:/nginx/html/projects/test-api/app/Console/Kernel.php
Parsing file:///c:/nginx/html/projects/test-api/app/Events/Event.php
Parsing file:///c:/nginx/html/projects/test-api/app/Events/ExampleEvent.php
Parsing file:///c:/nginx/html/projects/test-api/app/Exceptions/Handler.php
Parsing file:///c:/nginx/html/projects/test-api/app/Http/Controllers/Controller.php
Parsing file:///c:/nginx/html/projects/test-api/app/Http/Controllers/ExampleController.php
Parsing file:///c:/nginx/html/projects/test-api/app/Http/Middleware/Authenticate.php
Parsing file:///c:/nginx/html/projects/test-api/app/Http/Middleware/ExampleMiddleware.php
Parsing file:///c:/nginx/html/projects/test-api/app/Jobs/ExampleJob.php
Parsing file:///c:/nginx/html/projects/test-api/app/Jobs/Job.php
Parsing file:///c:/nginx/html/projects/test-api/app/Listeners/ExampleListener.php
Parsing file:///c:/nginx/html/projects/test-api/app/Providers/AppServiceProvider.php
Parsing file:///c:/nginx/html/projects/test-api/app/Providers/AuthServiceProvider.php
Parsing file:///c:/nginx/html/projects/test-api/app/Providers/EventServiceProvider.php
Parsing file:///c:/nginx/html/projects/test-api/app/User.php
Parsing file:///c:/nginx/html/projects/test-api/bootstrap/app.php
Parsing file:///c:/nginx/html/projects/test-api/database/factories/ModelFactory.php
Parsing file:///c:/nginx/html/projects/test-api/database/seeds/DatabaseSeeder.php
Parsing file:///c:/nginx/html/projects/test-api/public/index.php
Parsing file:///c:/nginx/html/projects/test-api/routes/web.php
Parsing file:///c:/nginx/html/projects/test-api/tests/ExampleTest.php
Parsing file:///c:/nginx/html/projects/test-api/tests/TestCase.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/autoload.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/composer/autoload_classmap.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/composer/autoload_files.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/composer/autoload_namespaces.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/composer/autoload_psr4.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/composer/autoload_real.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/composer/autoload_static.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/composer/ClassLoader.php
[Info  - 2:25:29 PM] Indexing project for dynamic references
Parsing file:///c:/nginx/html/projects/test-api/app/Console/Kernel.php
Parsing file:///c:/nginx/html/projects/test-api/app/Events/Event.php
Parsing file:///c:/nginx/html/projects/test-api/app/Events/ExampleEvent.php
Parsing file:///c:/nginx/html/projects/test-api/app/Exceptions/Handler.php
Parsing file:///c:/nginx/html/projects/test-api/app/Http/Controllers/Controller.php
Parsing file:///c:/nginx/html/projects/test-api/app/Http/Controllers/ExampleController.php
Parsing file:///c:/nginx/html/projects/test-api/app/Http/Middleware/Authenticate.php
Parsing file:///c:/nginx/html/projects/test-api/app/Http/Middleware/ExampleMiddleware.php
Parsing file:///c:/nginx/html/projects/test-api/app/Jobs/ExampleJob.php
Parsing file:///c:/nginx/html/projects/test-api/app/Jobs/Job.php
Parsing file:///c:/nginx/html/projects/test-api/app/Listeners/ExampleListener.php
Parsing file:///c:/nginx/html/projects/test-api/app/Providers/AppServiceProvider.php
Parsing file:///c:/nginx/html/projects/test-api/app/Providers/AuthServiceProvider.php
Parsing file:///c:/nginx/html/projects/test-api/app/Providers/EventServiceProvider.php
Parsing file:///c:/nginx/html/projects/test-api/app/User.php
Parsing file:///c:/nginx/html/projects/test-api/bootstrap/app.php
Parsing file:///c:/nginx/html/projects/test-api/database/factories/ModelFactory.php
Parsing file:///c:/nginx/html/projects/test-api/database/seeds/DatabaseSeeder.php
Parsing file:///c:/nginx/html/projects/test-api/public/index.php
Parsing file:///c:/nginx/html/projects/test-api/routes/web.php
Parsing file:///c:/nginx/html/projects/test-api/tests/ExampleTest.php
Parsing file:///c:/nginx/html/projects/test-api/tests/TestCase.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/autoload.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/composer/autoload_classmap.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/composer/autoload_files.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/composer/autoload_namespaces.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/composer/autoload_psr4.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/composer/autoload_real.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/composer/autoload_static.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/composer/ClassLoader.php
[Info  - 2:25:30 PM] 68 Packages
[Info  - 2:25:30 PM] Restored doctrine/inflector:1.1.0 from cache
[Info  - 2:25:30 PM] Restored doctrine/instantiator:1.0.5 from cache
[Info  - 2:25:30 PM] Restored fzaninotto/faker:1.6.0 from cache
[Info  - 2:25:31 PM] Restored hamcrest/hamcrest-php:1.2.2 from cache
[Info  - 2:25:31 PM] Restored illuminate/auth:5.4.19 from cache
[Info  - 2:25:31 PM] Restored illuminate/broadcasting:5.4.19 from cache
[Info  - 2:25:31 PM] Restored illuminate/bus:5.4.19 from cache
[Info  - 2:25:31 PM] Restored illuminate/cache:5.4.19 from cache
[Info  - 2:25:31 PM] Restored illuminate/config:5.4.19 from cache
[Info  - 2:25:31 PM] Restored illuminate/console:5.4.19 from cache
[Info  - 2:25:31 PM] Restored illuminate/container:5.4.19 from cache
[Info  - 2:25:31 PM] Restored illuminate/contracts:5.4.19 from cache
[Info  - 2:25:31 PM] Indexing illuminate/database:5.4.19 for definitions and static references
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/database/Capsule/Manager.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/database/Concerns/BuildsQueries.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/database/Concerns/ManagesTransactions.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/database/Connection.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/database/ConnectionInterface.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/database/ConnectionResolver.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/database/ConnectionResolverInterface.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/database/Connectors/ConnectionFactory.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/database/Connectors/Connector.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/database/Connectors/ConnectorInterface.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/database/Connectors/MySqlConnector.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/database/Connectors/PostgresConnector.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/database/Connectors/SQLiteConnector.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/database/Connectors/SqlServerConnector.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/database/Console/Migrations/BaseCommand.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/database/Console/Migrations/InstallCommand.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/database/Console/Migrations/MigrateCommand.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/database/Console/Migrations/MigrateMakeCommand.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/database/Console/Migrations/RefreshCommand.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/database/Console/Migrations/ResetCommand.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/database/Console/Migrations/RollbackCommand.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/database/Console/Migrations/StatusCommand.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/database/Console/Seeds/SeedCommand.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/database/Console/Seeds/SeederMakeCommand.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/database/DatabaseManager.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/database/DatabaseServiceProvider.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/database/DetectsDeadlocks.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/database/DetectsLostConnections.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/database/Eloquent/Builder.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/database/Eloquent/Collection.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/database/Eloquent/Concerns/GuardsAttributes.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/database/Eloquent/Concerns/HasAttributes.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/database/Eloquent/Concerns/HasEvents.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/database/Eloquent/Concerns/HasGlobalScopes.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/database/Eloquent/Concerns/HasRelationships.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/database/Eloquent/Concerns/HasTimestamps.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/database/Eloquent/Concerns/HidesAttributes.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/database/Eloquent/Concerns/QueriesRelationships.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/database/Eloquent/Factory.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/database/Eloquent/FactoryBuilder.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/database/Eloquent/JsonEncodingException.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/database/Eloquent/MassAssignmentException.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/database/Eloquent/Model.php
[Info  - 2:25:33 PM] Connection to server got closed. Server will restart.
[Info  - 2:25:39 PM] 3273 files total
[Info  - 2:25:39 PM] Indexing project for definitions and static references
Parsing file:///c:/nginx/html/projects/test-api/app/Console/Kernel.php
Parsing file:///c:/nginx/html/projects/test-api/app/Events/Event.php
Parsing file:///c:/nginx/html/projects/test-api/app/Events/ExampleEvent.php
Parsing file:///c:/nginx/html/projects/test-api/app/Exceptions/Handler.php
Parsing file:///c:/nginx/html/projects/test-api/app/Http/Controllers/Controller.php
Parsing file:///c:/nginx/html/projects/test-api/app/Http/Controllers/ExampleController.php
Parsing file:///c:/nginx/html/projects/test-api/app/Http/Middleware/Authenticate.php
Parsing file:///c:/nginx/html/projects/test-api/app/Http/Middleware/ExampleMiddleware.php
Parsing file:///c:/nginx/html/projects/test-api/app/Jobs/ExampleJob.php
Parsing file:///c:/nginx/html/projects/test-api/app/Jobs/Job.php
Parsing file:///c:/nginx/html/projects/test-api/app/Listeners/ExampleListener.php
Parsing file:///c:/nginx/html/projects/test-api/app/Providers/AppServiceProvider.php
Parsing file:///c:/nginx/html/projects/test-api/app/Providers/AuthServiceProvider.php
Parsing file:///c:/nginx/html/projects/test-api/app/Providers/EventServiceProvider.php
Parsing file:///c:/nginx/html/projects/test-api/app/User.php
Parsing file:///c:/nginx/html/projects/test-api/bootstrap/app.php
Parsing file:///c:/nginx/html/projects/test-api/database/factories/ModelFactory.php
Parsing file:///c:/nginx/html/projects/test-api/database/seeds/DatabaseSeeder.php
Parsing file:///c:/nginx/html/projects/test-api/public/index.php
Parsing file:///c:/nginx/html/projects/test-api/routes/web.php
Parsing file:///c:/nginx/html/projects/test-api/tests/ExampleTest.php
Parsing file:///c:/nginx/html/projects/test-api/tests/TestCase.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/autoload.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/composer/autoload_classmap.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/composer/autoload_files.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/composer/autoload_namespaces.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/composer/autoload_psr4.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/composer/autoload_real.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/composer/autoload_static.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/composer/ClassLoader.php
[Info  - 2:25:39 PM] Indexing project for dynamic references
Parsing file:///c:/nginx/html/projects/test-api/app/Console/Kernel.php
Parsing file:///c:/nginx/html/projects/test-api/app/Events/Event.php
Parsing file:///c:/nginx/html/projects/test-api/app/Events/ExampleEvent.php
Parsing file:///c:/nginx/html/projects/test-api/app/Exceptions/Handler.php
Parsing file:///c:/nginx/html/projects/test-api/app/Http/Controllers/Controller.php
Parsing file:///c:/nginx/html/projects/test-api/app/Http/Controllers/ExampleController.php
Parsing file:///c:/nginx/html/projects/test-api/app/Http/Middleware/Authenticate.php
Parsing file:///c:/nginx/html/projects/test-api/app/Http/Middleware/ExampleMiddleware.php
Parsing file:///c:/nginx/html/projects/test-api/app/Jobs/ExampleJob.php
Parsing file:///c:/nginx/html/projects/test-api/app/Jobs/Job.php
Parsing file:///c:/nginx/html/projects/test-api/app/Listeners/ExampleListener.php
Parsing file:///c:/nginx/html/projects/test-api/app/Providers/AppServiceProvider.php
Parsing file:///c:/nginx/html/projects/test-api/app/Providers/AuthServiceProvider.php
Parsing file:///c:/nginx/html/projects/test-api/app/Providers/EventServiceProvider.php
Parsing file:///c:/nginx/html/projects/test-api/app/User.php
Parsing file:///c:/nginx/html/projects/test-api/bootstrap/app.php
Parsing file:///c:/nginx/html/projects/test-api/database/factories/ModelFactory.php
Parsing file:///c:/nginx/html/projects/test-api/database/seeds/DatabaseSeeder.php
Parsing file:///c:/nginx/html/projects/test-api/public/index.php
Parsing file:///c:/nginx/html/projects/test-api/routes/web.php
Parsing file:///c:/nginx/html/projects/test-api/tests/ExampleTest.php
Parsing file:///c:/nginx/html/projects/test-api/tests/TestCase.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/autoload.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/composer/autoload_classmap.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/composer/autoload_files.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/composer/autoload_namespaces.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/composer/autoload_psr4.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/composer/autoload_real.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/composer/autoload_static.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/composer/ClassLoader.php
[Info  - 2:25:40 PM] 68 Packages
[Info  - 2:25:40 PM] Restored doctrine/inflector:1.1.0 from cache
[Info  - 2:25:40 PM] Restored doctrine/instantiator:1.0.5 from cache
[Info  - 2:25:40 PM] Restored fzaninotto/faker:1.6.0 from cache
[Info  - 2:25:40 PM] Restored hamcrest/hamcrest-php:1.2.2 from cache
[Info  - 2:25:40 PM] Restored illuminate/auth:5.4.19 from cache
[Info  - 2:25:40 PM] Restored illuminate/broadcasting:5.4.19 from cache
[Info  - 2:25:40 PM] Restored illuminate/bus:5.4.19 from cache
[Info  - 2:25:40 PM] Restored illuminate/cache:5.4.19 from cache
[Info  - 2:25:40 PM] Restored illuminate/config:5.4.19 from cache
[Info  - 2:25:40 PM] Restored illuminate/console:5.4.19 from cache
[Info  - 2:25:40 PM] Restored illuminate/container:5.4.19 from cache
[Info  - 2:25:40 PM] Restored illuminate/contracts:5.4.19 from cache
[Info  - 2:25:40 PM] Indexing illuminate/database:5.4.19 for definitions and static references
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/database/Capsule/Manager.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/database/Concerns/BuildsQueries.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/database/Concerns/ManagesTransactions.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/database/Connection.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/database/ConnectionInterface.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/database/ConnectionResolver.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/database/ConnectionResolverInterface.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/database/Connectors/ConnectionFactory.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/database/Connectors/Connector.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/database/Connectors/ConnectorInterface.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/database/Connectors/MySqlConnector.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/database/Connectors/PostgresConnector.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/database/Connectors/SQLiteConnector.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/database/Connectors/SqlServerConnector.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/database/Console/Migrations/BaseCommand.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/database/Console/Migrations/InstallCommand.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/database/Console/Migrations/MigrateCommand.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/database/Console/Migrations/MigrateMakeCommand.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/database/Console/Migrations/RefreshCommand.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/database/Console/Migrations/ResetCommand.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/database/Console/Migrations/RollbackCommand.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/database/Console/Migrations/StatusCommand.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/database/Console/Seeds/SeedCommand.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/database/Console/Seeds/SeederMakeCommand.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/database/DatabaseManager.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/database/DatabaseServiceProvider.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/database/DetectsDeadlocks.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/database/DetectsLostConnections.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/database/Eloquent/Builder.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/database/Eloquent/Collection.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/database/Eloquent/Concerns/GuardsAttributes.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/database/Eloquent/Concerns/HasAttributes.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/database/Eloquent/Concerns/HasEvents.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/database/Eloquent/Concerns/HasGlobalScopes.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/database/Eloquent/Concerns/HasRelationships.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/database/Eloquent/Concerns/HasTimestamps.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/database/Eloquent/Concerns/HidesAttributes.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/database/Eloquent/Concerns/QueriesRelationships.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/database/Eloquent/Factory.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/database/Eloquent/FactoryBuilder.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/database/Eloquent/JsonEncodingException.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/database/Eloquent/MassAssignmentException.php
Parsing file:///c:/nginx/html/projects/test-api/vendor/illuminate/database/Eloquent/Model.php
[Error - 2:25:42 PM] Connection to server got closed. Server will not be restarted.
```

Error Message in the dev tools:
```
[Extension Host] TypeError: Argument 1 passed to LanguageServer\ParserHelpers::isConstantFetch() must be an instance of Microsoft\PhpParser\Node, instance of Microsoft\PhpParser\MissingToken given, called in C:\Users\Jens\.vscode\extensions\felixfbecker.php-intellisense-1.2.2\vendor\felixfbecker\language-server\src\DefinitionResolver.php on line 620 and defined in C:\Users\Jens\.vscode\extensions\felixfbecker.php-intellisense-1.2.2\vendor\felixfbecker\language-server\src\ParserHelpers.php:10
Stack trace:
#0 C:\Users\Jens\.vscode\extensions\felixfbecker.php-intellisense-1.2.2\vendor\felixfbecker\language-server\src\DefinitionResolver.php(620): LanguageServer\ParserHelpers::isConstantFetch(Object(Microsoft\PhpParser\MissingToken))
#1 C:\Users\Jens\.vscode\extensions\felixfbecker.php-intellisense-1.2.2\vendor\felixfbecker\language-server\src\DefinitionResolver.php(355): LanguageServer\DefinitionResolver->resolveExpressionNodeToType(Object(Microsoft\PhpParser\MissingToken))
#2 C:\Users\Jens\.vscode\extensions\felixfbecker.php-intellisense-1.2.2\vendor\felixfbecker\language-server\src\DefinitionResolver.php(282): LanguageServer\DefinitionResolver->resolveMemberAccessExpressionNodeToFqn(Object(Microsoft\PhpParser\Node\Expression\MemberAccessExpression))
#3 C:\Users\Jens\.vscode\extensions\felixfbecker.php-intellisense-1.2.2\vendor\felixfbecker\language-server\src\TreeAnalyzer.php(102): LanguageServer\DefinitionResolver->resolveReferenceNodeToFqn(Object(Microsoft\PhpParser\Node\Expression\MemberAccessExpression))
#4 C:\Users\Jens\.vscode\extensions\felixfbecker.php-intellisense-1.2.2\vendor\felixfbecker\language-server\src\TreeAnalyzer.php(62): LanguageServer\TreeAnalyzer->update(Object(Microsoft\PhpParser\Node\Expression\MemberAccessExpression))
#5 C:\Users\Jens\.vscode\extensions\felixfbecker.php-intellisense-1.2.2\vendor\felixfbecker\language-server\src\TreeAnalyzer.php(138): LanguageServer\TreeAnalyzer->collectDefinitionsAndReferences(Object(Microsoft\PhpParser\Node\Statement\ExpressionStatement))
#6 C:\Users\Jens\.vscode\extensions\felixfbecker.php-intellisense-1.2.2\vendor\felixfbecker\language-server\src\TreeAnalyzer.php(55): LanguageServer\TreeAnalyzer->update(Object(Microsoft\PhpParser\Node\Statement\ExpressionStatement))
#7 C:\Users\Jens\.vscode\extensions\felixfbecker.php-intellisense-1.2.2\vendor\felixfbecker\language-server\src\TreeAnalyzer.php(138): LanguageServer\TreeAnalyzer->collectDefinitionsAndReferences(Object(Microsoft\PhpParser\Node\Statement\CompoundStatementNode))
#8 C:\Users\Jens\.vscode\extensions\felixfbecker.php-intellisense-1.2.2\vendor\felixfbecker\language-server\src\TreeAnalyzer.php(62): LanguageServer\TreeAnalyzer->update(Object(Microsoft\PhpParser\Node\Statement\CompoundStatementNode))
#9 C:\Users\Jens\.vscode\extensions\felixfbecker.php-intellisense-1.2.2\vendor\felixfbecker\language-server\src\TreeAnalyzer.php(138): LanguageServer\TreeAnalyzer->collectDefinitionsAndReferences(Object(Microsoft\PhpParser\Node\Expression\AnonymousFunctionCreationExpression))
#10 C:\Users\Jens\.vscode\extensions\felixfbecker.php-intellisense-1.2.2\vendor\felixfbecker\language-server\src\TreeAnalyzer.php(62): LanguageServer\TreeAnalyzer->update(Object(Microsoft\PhpParser\Node\Expression\AnonymousFunctionCreationExpression))
#11 C:\Users\Jens\.vscode\extensions\felixfbecker.php-intellisense-1.2.2\vendor\felixfbecker\language-server\src\TreeAnalyzer.php(138): LanguageServer\TreeAnalyzer->collectDefinitionsAndReferences(Object(Microsoft\PhpParser\Node\Expression\ObjectCreationExpression))
#12 C:\Users\Jens\.vscode\extensions\felixfbecker.php-intellisense-1.2.2\vendor\felixfbecker\language-server\src\TreeAnalyzer.php(62): LanguageServer\TreeAnalyzer->update(Object(Microsoft\PhpParser\Node\Expression\ObjectCreationExpression))
#13 C:\Users\Jens\.vscode\extensions\felixfbecker.php-intellisense-1.2.2\vendor\felixfbecker\language-server\src\TreeAnalyzer.php(138): LanguageServer\TreeAnalyzer->collectDefinitionsAndReferences(Object(Microsoft\PhpParser\Node\Expression\AssignmentExpression))
#14 C:\Users\Jens\.vscode\extensions\felixfbecker.php-intellisense-1.2.2\vendor\felixfbecker\language-server\src\TreeAnalyzer.php(62): LanguageServer\TreeAnalyzer->update(Object(Microsoft\PhpParser\Node\Expression\AssignmentExpression))
#15 C:\Users\Jens\.vscode\extensions\felixfbecker.php-intellisense-1.2.2\vendor\felixfbecker\language-server\src\TreeAnalyzer.php(138): LanguageServer\TreeAnalyzer->collectDefinitionsAndReferences(Object(Microsoft\PhpParser\Node\Statement\ExpressionStatement))
#16 C:\Users\Jens\.vscode\extensions\felixfbecker.php-intellisense-1.2.2\vendor\felixfbecker\language-server\src\TreeAnalyzer.php(55): LanguageServer\TreeAnalyzer->update(Object(Microsoft\PhpParser\Node\Statement\ExpressionStatement))
#17 C:\Users\Jens\.vscode\extensions\felixfbecker.php-intellisense-1.2.2\vendor\felixfbecker\language-server\src\TreeAnalyzer.php(138): LanguageServer\TreeAnalyzer->collectDefinitionsAndReferences(Object(Microsoft\PhpParser\Node\Statement\CompoundStatementNode))
#18 C:\Users\Jens\.vscode\extensions\felixfbecker.php-intellisense-1.2.2\vendor\felixfbecker\language-server\src\TreeAnalyzer.php(62): LanguageServer\TreeAnalyzer->update(Object(Microsoft\PhpParser\Node\Statement\CompoundStatementNode))
#19 C:\Users\Jens\.vscode\extensions\felixfbecker.php-intellisense-1.2.2\vendor\felixfbecker\language-server\src\TreeAnalyzer.php(138): LanguageServer\TreeAnalyzer->collectDefinitionsAndReferences(Object(Microsoft\PhpParser\Node\MethodDeclaration))
#20 C:\Users\Jens\.vscode\extensions\felixfbecker.php-intellisense-1.2.2\vendor\felixfbecker\language-server\src\TreeAnalyzer.php(55): LanguageServer\TreeAnalyzer->update(Object(Microsoft\PhpParser\Node\MethodDeclaration))
#21 C:\Users\Jens\.vscode\extensions\felixfbecker.php-intellisense-1.2.2\vendor\felixfbecker\language-server\src\TreeAnalyzer.php(138): LanguageServer\TreeAnalyzer->collectDefinitionsAndReferences(Object(Microsoft\PhpParser\Node\ClassMembersNode))
#22 C:\Users\Jens\.vscode\extensions\felixfbecker.php-intellisense-1.2.2\vendor\felixfbecker\language-server\src\TreeAnalyzer.php(62): LanguageServer\TreeAnalyzer->update(Object(Microsoft\PhpParser\Node\ClassMembersNode))
#23 C:\Users\Jens\.vscode\extensions\felixfbecker.php-intellisense-1.2.2\vendor\felixfbecker\language-server\src\TreeAnalyzer.php(138): LanguageServer\TreeAnalyzer->collectDefinitionsAndReferences(Object(Microsoft\PhpParser\Node\Statement\ClassDeclaration))
#24 C:\Users\Jens\.vscode\extensions\felixfbecker.php-intellisense-1.2.2\vendor\felixfbecker\language-server\src\TreeAnalyzer.php(55): LanguageServer\TreeAnalyzer->update(Object(Microsoft\PhpParser\Node\Statement\ClassDeclaration))
#25 C:\Users\Jens\.vscode\extensions\felixfbecker.php-intellisense-1.2.2\vendor\felixfbecker\language-server\src\TreeAnalyzer.php(41): LanguageServer\TreeAnalyzer->collectDefinitionsAndReferences(Object(Microsoft\PhpParser\Node\SourceFileNode))
#26 C:\Users\Jens\.vscode\extensions\felixfbecker.php-intellisense-1.2.2\vendor\felixfbecker\language-server\src\PhpDocument.php(156): LanguageServer\TreeAnalyzer->__construct(Object(Microsoft\PhpParser\Parser), '<?php\n\nnamespac...', Object(phpDocumentor\Reflection\DocBlockFactory), Object(LanguageServer\DefinitionResolver), 'file:///c:/ngin...')
#27 C:\Users\Jens\.vscode\extensions\felixfbecker.php-intellisense-1.2.2\vendor\felixfbecker\language-server\src\PhpDocument.php(112): LanguageServer\PhpDocument->updateContent('<?php\n\nnamespac...')
#28 C:\Users\Jens\.vscode\extensions\felixfbecker.php-intellisense-1.2.2\vendor\felixfbecker\language-server\src\PhpDocumentLoader.php(141): LanguageServer\PhpDocument->__construct('file:///c:/ngin...', '<?php\n\nnamespac...', Object(LanguageServer\Index\Index), Object(Microsoft\PhpParser\Parser), Object(phpDocumentor\Reflection\DocBlockFactory), Object(LanguageServer\DefinitionResolver))
#29 C:\Users\Jens\.vscode\extensions\felixfbecker.php-intellisense-1.2.2\vendor\felixfbecker\language-server\src\PhpDocumentLoader.php(120): LanguageServer\PhpDocumentLoader->create('file:///c:/ngin...', '<?php\n\nnamespac...')
#30 [internal function]: LanguageServer\PhpDocumentLoader->LanguageServer\{closure}()
#31 C:\Users\Jens\.vscode\extensions\felixfbecker.php-intellisense-1.2.2\vendor\sabre\event\lib\coroutine.php(70): Generator->send('<?php\n\nnamespac...')
#32 C:\Users\Jens\.vscode\extensions\felixfbecker.php-intellisense-1.2.2\vendor\sabre\event\lib\Promise.php(242): Sabre\Event\{closure}('<?php\n\nnamespac...')
#33 C:\Users\Jens\.vscode\extensions\felixfbecker.php-intellisense-1.2.2\vendor\sabre\event\lib\Loop\Loop.php(261): Sabre\Event\Promise->Sabre\Event\{closure}()
#34 C:\Users\Jens\.vscode\extensions\felixfbecker.php-intellisense-1.2.2\vendor\sabre\event\lib\Loop\Loop.php(215): Sabre\Event\Loop\Loop->runNextTicks()
#35 C:\Users\Jens\.vscode\extensions\felixfbecker.php-intellisense-1.2.2\vendor\sabre\event\lib\Loop\Loop.php(194): Sabre\Event\Loop\Loop->tick(true)
#36 C:\Users\Jens\.vscode\extensions\felixfbecker.php-intellisense-1.2.2\vendor\sabre\event\lib\Loop\functions.php(122): Sabre\Event\Loop\Loop->run()
#37 C:\Users\Jens\.vscode\extensions\felixfbecker.php-intellisense-1.2.2\vendor\felixfbecker\language-server\bin\php-language-server.php(50): Sabre\Event\Loop\run()
#38 {main}
```

**Comment by jens1o** [comment]
When hovering over `new \SplFileInfo`, I can see the bracket in the hover: 
image

**Comment by felixfbecker** [comment]
> When hovering over new \SplFileInfo, I can see the bracket in the hover:

This is a regression we will accept, there is no pretty-printing yet in the new parser, so it is shown as in the definition.

> It looks like inline variable overwrites aren't respected:

Not sure if that worked reliably on master.

> I would like to get notified that I'm breaking out of restrictions. I'm not allowed to return false, maybe you can implement that?

That would mean type-checking like in TypeScript, we don't currently do that, but it is a valid feature request - not in scope for this PR though.

**Comment by jens1o** [comment]
Okay, I'll create an issue asap this gets merged. I really like the effort and work, and I just want to improve its experience.

**Comment by roblourens** [comment]
Thanks for all the reports. I'll work on them this week.

**Comment by jens1o** [comment]
Would love to see that the next testable extension will be based on `1.3.0`, so it will be started before actually editing a file.

**Comment by roblourens** [comment]
I fixed one of the MissingToken-related errors and the CI issue. I'm looking at the other error now. Here's my list of issues that need to be addressed:

- [ ] Another error regarding MissingToken in 'lumen' project
- [ ] Nullable types not implemented: new in 7.1
  -  https://github.com/Microsoft/tolerant-php-parser/issues/97
- [ ] Include, require in expressions marked as errors
  - Parser
- [ ] Using `new static` without parens
- [ ] Doesn't give intellisense based on function return type
  - Should work, maybe due to some other error
  - Clone that repo to try specific scenario

I will investigate the other error asap. For the other issues, I personally think that the best way to move forward is to file issues for them, wrap up this PR, and handle them separately. I the best thing for this project is to move on and get this PR into master. For example, if anyone else wants to help out or contribute to this repo, I think it's very difficult with a huge commit like this still pending.

Thoughts @felixfbecker?

**Comment by jens1o** [comment]
May I ask you to publish a new version, because then I don't get annoyed about that they is a new version of this extension. I really like your effort :) But till you release a new version, I get this very often when I do a typo.

I am not Felix, but I like your idea concerning the further future of this pr.

**Comment by jens1o** [comment]
I do not know whether this addresses this pr or should be handled in an external issue, but this is really bad:
image
(I'm hovering about `$notification`.)

Code:
```php
<?php
require_once './vendor/autoload.php';

use Joli\JoliNotif\Notification;
use Joli\JoliNotif\NotifierFactory;

// Create a Notifier
$notifier = NotifierFactory::create();

// Create your notification
$notification =
    (new Notification())
    ->setTitle('Update complete')
    ->setBody('Updates of the dependencies were successfully applied!')
;

// Send it
$notifier->send($notification);
```

composer.json: 
```json
{
    "require": {
        "jolicode/jolinotif": "^1.1"
    }
}
```

**Comment by jens1o** [comment]
I found another thing:
Static functions return types won't be always recognized.
Example:
image
image

Require composer dependency `sabre/http` and try to get info about `Sabre\HTTP\Sapi::getRequest` other than `mixed`.

File: src/DefinitionResolver.php [hunk 17]
```diff
@@ -723,58 +931,65 @@ private static function resolveClassNameToType(Node $class): Type
...
     {
-        if (
-            $node instanceof Node\Expr\FuncCall
-            && $node->name instanceof Node\Name
-            && strtolower((string)$node->name) === 'define'
-            && isset($node->args[0])
-            && $node->args[0]->value instanceof Node\Scalar\String_
-            && isset($node->args[1])
-        ) {
+        if (ParserHelpers::isConstDefineExpression($node)) {
```
Comment (felixfbecker) [inline src/DefinitionResolver.php]: does this check whether `define` is called correctly with two parameters?

File: src/FqnUtilities.php [hunk 18]
```diff
@@ -0,0 +1,34 @@
...
+
+class FqnUtilities
+{
+    /**
+     * Returns all possible FQNs in a type
+     *
+     * @param Type|null $type
+     * @return string[]
+     */
+    public static function getFqnsFromType($type): array
```
Comment (felixfbecker) [inline src/FqnUtilities.php]: Is there any benefit in having this as a class with static methods instead of pure functions?

File: src/Index/Index.php [hunk 19]
```diff
@@ -26,7 +26,7 @@ class Index implements ReadableIndex, \Serializable
      *
      * @var string[][]
      */
-    private $references = [];
+    public $references = [];
```
Comment (felixfbecker) [inline src/Index/Index.php]: why does this have to be public?

File: src/LanguageServer.php [hunk 20]
```diff
@@ -8,23 +8,18 @@
...
-    TextDocumentIdentifier,
     CompletionOptions
 };
 use LanguageServer\FilesFinder\{FilesFinder, ClientFilesFinder, FileSystemFilesFinder};
 use LanguageServer\ContentRetriever\{ContentRetriever, ClientContentRetriever, FileSystemContentRetriever};
 use LanguageServer\Index\{DependenciesIndex, GlobalIndex, Index, ProjectIndex, StubsIndex};
 use LanguageServer\Cache\{FileSystemCache, ClientCache};
 use AdvancedJsonRpc;
-use Sabre\Event\{Loop, Promise};
+use Sabre\Event\{Promise};
```
Comment (felixfbecker) [inline src/LanguageServer.php]: Shouldn't be a group-use statement

File: src/ParserHelpers.php [hunk 21]
```diff
@@ -0,0 +1,128 @@
+<?php
+declare(strict_types=1);
+
+namespace LanguageServer;
+
+use Microsoft\PhpParser;
+use Microsoft\PhpParser\Node;
+
+class ParserHelpers
```
Comment (felixfbecker) [inline src/ParserHelpers.php]: What's the benefit of having this as a class over pure functions?

File: src/ParserHelpers.php [hunk 22]
```diff
@@ -0,0 +1,128 @@
...
+{
+    public static function isConstantFetch(Node $node) : bool
+    {
+        $parent = $node->parent;
+        return
+            (
+            $node instanceof Node\QualifiedName &&
+            (
+//                $node->parent instanceof Node\Statement\ExpressionStatement ||
```
Comment (felixfbecker) [inline src/ParserHelpers.php]: why is this commented out?

File: src/ParserKind.php [hunk 23]
```diff
@@ -0,0 +1,11 @@
+<?php
+
+namespace LanguageServer;
+
+class ParserKind
```
Comment (felixfbecker) [inline src/ParserKind.php]: Is this still needed?

File: src/Protocol/Range.php [hunk 24]
```diff
@@ -29,30 +30,16 @@ class Range
      * @param Node $node
      * @return self
      */
-    public static function fromNode(Node $node)
+    public static function fromNode($node)
```
Comment (felixfbecker) [inline src/Protocol/Range.php]: type hint

File: src/Protocol/SymbolInformation.php [hunk 25]
```diff
@@ -44,66 +45,80 @@ class SymbolInformation
...
+        //         $symbol->name = (string)$node;
+        //     } else if ($node instanceof Node\Expr\Assign || $node instanceof Node\Expr\AssignOp) {
+        //         $symbol->name = $node->var->name;
+        //     } else if ($node instanceof Node\Expr\ClosureUse) {
+        //         $symbol->name = $node->var;
+        //     } else if (isset($node->name)) {
+        //         $symbol->name = (string)$node->name;
+        //     } else {
+        //         return null;
+        //     }
```
Comment (felixfbecker) [inline src/Protocol/SymbolInformation.php]: What's up with this comment section?

File: src/Server/TextDocument.php [hunk 26]
```diff
@@ -67,7 +49,7 @@ class TextDocument
     /**
      * @var ReadableIndex
      */
-    protected $index;
+    public $index;
```
Comment (felixfbecker) [inline src/Server/TextDocument.php]: does this have to be public?

File: src/Server/TextDocument.php [hunk 27]
```diff
@@ -80,12 +62,12 @@ class TextDocument
...
+     * @param PhpDocumentLoader $documentLoader
      * @param DefinitionResolver $definitionResolver
-     * @param LanguageClient     $client
-     * @param ReadableIndex      $index
-     * @param \stdClass          $composerJson
-     * @param \stdClass          $composerLock
+     * @param LanguageClient $client
+     * @param ReadableIndex $index
+     * @param \stdClass $composerJson
+     * @param \stdClass $composerLock
```
Comment (felixfbecker) [inline src/Server/TextDocument.php]: Is there any reason you reformatted all these docblocks?

File: src/TreeAnalyzer.php [hunk 28]
```diff
@@ -0,0 +1,185 @@
...
+class TreeAnalyzer
+{
+    private $parser;
+
+    /** @var Node */
+    private $stmts;
+
+    private $diagnostics;
+
+    private $content;
```
Comment (felixfbecker) [inline src/TreeAnalyzer.php]: These should have `@var` comments

File: src/TreeAnalyzer.php [hunk 29]
```diff
@@ -0,0 +1,185 @@
...
+                    }
+                }
+                continue;
+            }
+
+            if ($node instanceof Node) {
+                $this->update($node);
+            }
+
+            if (($_error = PhpParser\DiagnosticsProvider::checkDiagnostics($node)) !== null) {
```
Comment (felixfbecker) [inline src/TreeAnalyzer.php]: why the underscore?

File: src/TreeAnalyzer.php [hunk 30]
```diff
@@ -0,0 +1,185 @@
...
+                    ),
+                    null,
+                    DiagnosticSeverity::ERROR,
+                    'php'
+                );
+            }
+        }
+    }
+
+    public function update($node)
```
Comment (felixfbecker) [inline src/TreeAnalyzer.php]: This should have a docblock explaining what it does

File: src/TreeAnalyzer.php [hunk 31]
```diff
@@ -0,0 +1,185 @@
...
+        return $this->stmts;
+    }
+    /**
+     * Returns the URI of the document
+     *
+     * @return string
+     */
+    public function getUri(): string
+    {
+        return $this->uri;
```
Comment (felixfbecker) [inline src/TreeAnalyzer.php]: I don't see this property and most of the above being defined or used in the class

File: src/utils.php [hunk 32]
```diff
@@ -189,3 +171,8 @@ function getVendorDir(\stdClass $composerJson = null): string
 {
     return $composerJson->config->{'vendor-dir'} ?? 'vendor';
 }
+
+function strStartsWith(string $haystack, string $prefix): bool
+{
+    return empty($prefix) || strpos($haystack, $prefix) === 0;
```
Comment (felixfbecker) [inline src/utils.php]: Is this function really needed? `substr($haystack, 0, strlen($prefix)) === $prefix` should be faster (depending on heystack size) because it doesn't have to search the whole string, just check the first `strlen($prefix)` characters for identity.  In a loop you only have to get the prefix length once. And it also returns `true` for an empty prefix, since `substr($haystack, 0, 0)` is the empty string.

File: tests/Server/TextDocument/ParseErrorsTest.php [hunk 33]
```diff
@@ -62,42 +64,91 @@ public function testParseErrorsArePublishedAsDiagnostics()
...
                 'code' => null,
                 'source' => 'php',
-                'message' => "Namespace declaration statement has to be the very first statement in the script"
+                'message' => "'Name' expected."
             ]]
         ], json_decode(json_encode($this->args), true));
     }
+
+    // This diagnostic not yet implemented in tolerant-php-parser
+    // public function testParseErrorsWithOnlyStartLine()
```
Comment (felixfbecker) [inline tests/Server/TextDocument/ParseErrorsTest.php]: This should use `$this->markTestIncomplete('Not yet implemented in tolerant-php-parser')` so this doesn't just disappear from the test results

File: tests/Validation/ValidationTest.php [hunk 34]
```diff
@@ -0,0 +1,196 @@
...
+                file_put_contents($outputFile, json_encode($actualValues, JSON_PRETTY_PRINT|JSON_UNESCAPED_SLASHES));
+            }
+
+            throw $e;
+        }
+    }
+
+    private function getActualTestValues($filename, $fileContents): array
+    {
+        global $frameworksDir;
```
Comment (felixfbecker) [inline tests/Validation/ValidationTest.php]: No globals please. I only see it being used in this class, so a private property should be fine.

File: tests/Validation/ValidationTest.php [hunk 35]
```diff
@@ -0,0 +1,196 @@
...
+        $definitionResolver = new DefinitionResolver($index);
+
+        $document = new PhpDocument($filename, $fileContents, $index, $parser, $docBlockFactory, $definitionResolver);
+
+        $actualRefs = $index->references;
+        $this->filterSkippedReferences($actualRefs);
+        $actualDefs = $this->getTestValuesFromDefs($document->getDefinitions());
+
+        // TODO - there's probably a more PHP-typical way to do this. Need to compare the objects parsed from json files
+        // to the real results. json_decode returns stdClass Objects, not arrays.
```
Comment (felixfbecker) [inline tests/Validation/ValidationTest.php]: `json_decode` returns associative arrays if you set the second parameter to `true`.
`==` and `assertEquals` return true if objects are of the same class and have the same properties and arrays have the same exact members at the same indices, recursively.

File: tests/Validation/ValidationTest.php [hunk 36]
```diff
@@ -0,0 +1,196 @@
...
+    }
+
+    /**
+     * @param $definitions Definition[]
+     * @return array|\array[]
+     */
+    private function getTestValuesFromDefs($definitions): array
+    {
+        // TODO - use reflection to read these properties
+        $propertyNames = ['extends', 'isGlobal', 'isStatic', 'canBeInstantiated', 'symbolInformation', 'type', 'documentation'];
```
Comment (felixfbecker) [inline tests/Validation/ValidationTest.php]: `get_class_vars(Definition::class)` should do the trick.

File: tests/Validation/ValidationTest.php [hunk 37]
```diff
@@ -0,0 +1,196 @@
...
+     */
+    private function filterSkippedReferences(&$references)
+    {
+        $skipped = [
+            'false', 'true', 'null', 'FALSE', 'TRUE', 'NULL',
+            '__', // magic constants are treated as normal constants
+            'Exception', 'Error', // catch exception types missing from old definition resolver
+            'Trait', // use Trait references are missing from old definition resolve
+            '->tableAlias', '->realField', '->field', '->first_name', '->last_name', '->quoteMatch', '->idCol', '->timeCol', '->dataCol',
+            'pathToUri', 'uriToPath' // group function use declarations are broken in old definition resolver
```
Comment (felixfbecker) [inline tests/Validation/ValidationTest.php]: I don't understand what is going on in this method - what is "skipped" here?

File: tests/Validation/ValidationTest.php [hunk 38]
```diff
@@ -0,0 +1,196 @@
...
+use LanguageServer\Protocol\Message;
+use AdvancedJsonRpc;
+use RecursiveDirectoryIterator;
+use RecursiveIteratorIterator;
+use Sabre\Event\Loop;
+use Microsoft\PhpParser;
+
+$frameworksDir = realpath(__DIR__ . '/../../validation/frameworks');
+
+class ValidationTest extends TestCase
```
Comment (felixfbecker) [inline tests/Validation/ValidationTest.php]: Could you document what the ValidationTests mean compared to the unit tests that work with the `fixtures` folder? Shall all tests be written using the JSON files going forward?

File: src/CompletionProvider.php [hunk 39]
```diff
@@ -169,122 +197,112 @@ public function provideCompletion(PhpDocument $doc, Position $pos): CompletionLi
...
+
+                    $item->insertText = $fqn;
                     $list->items[] = $item;
                 }
             }
-            // Suggest keywords
-            if ($node instanceof Node\Name && $node->getAttribute('parentNode') instanceof Node\Expr\ConstFetch) {
+
+            if (!isset($creation)) {
                 foreach (self::KEYWORDS as $keyword) {
```
Comment (jens1o) [inline src/CompletionProvider.php]: maybe add `true`, `false` and `null` to the keywords?

Comment (felixfbecker) [inline src/CompletionProvider.php]: While yes, that could be done, there are already enough changes in this PR and that would have nothing to do with the parser adoption.

Comment (jens1o) [inline src/CompletionProvider.php]: Okay, I'll create a pr as soon this gets merged 😋

**Comment by jens1o** [comment]
Another thing:

It seems that you break the feature that it will propose classes after the `new` keyword.
fc776b00-0386-4f36-8f0e-74c512776b5c

File: Performance.php [hunk 40]
```diff
@@ -0,0 +1,76 @@
+<?php
+
+namespace LanguageServer\Tests;
```
Comment (roblourens) [inline Performance.php]: I'm hesitant to write an assert that a test runs in less than N seconds. You can really only compare performance between two runs on a given machine under controlled conditions.

If you want to do this in Travis or something (which would be awesome) maybe we could have it check out the previous version and run the test, then immediately check out the new version and run the test, and run several times and average the runs. But you still have to think about other things happening on the same machine, filesystem caching, other environmental things out of our control, so it might still end up flaky. I think doing this right is out of scope of this PR.

File: src/CompletionProvider.php [hunk 41]
```diff
@@ -372,38 +393,37 @@ private function suggestVariablesAtNode(Node $node, string $namePrefix = ''): ar
...
-                }
-                foreach ($this->findVariableDefinitionsInNode($child, $namePrefix) as $var) {
-                    $vars[] = $var;
+
+        $isAssignmentToVariable = function ($node) use ($namePrefix) {
+            return $node instanceof Node\Expression\AssignmentExpression
+                && $node->leftOperand instanceof Node\Expression\Variable
+                && (empty($namePrefix) || strpos($node->leftOperand->getName(), $namePrefix) !== false);
+        };
+        $isNotFunctionLike = function ($node) {
```
Comment (roblourens) [inline src/CompletionProvider.php]: This is a pure function and isn't using anything from the environment. Are you talking about `isAssignmentToVariable`?

Comment (felixfbecker) [inline src/CompletionProvider.php]: With pure helper function, I meant a stand-alone function declaration instead of an anonymous function. Ideally `isAssignmentToVariable` is also made pure and changed.

File: src/DefinitionResolver.php [hunk 42]
```diff
@@ -33,35 +41,43 @@ public function __construct(ReadableIndex $index)
...
-        $defLine->setAttribute('comments', []);
-        if (isset($defLine->stmts)) {
-            $defLine->stmts = [];
+            $defLine = $node->getText();
         }
-        $defText = $this->prettyPrinter->prettyPrint([$defLine]);
-        return strstr($defText, "\n", true) ?: $defText;
+
+        // Trim string to only include first line
+        $defLine = \rtrim(\strtok($defLine, "\n"), "\r");
```
Comment (roblourens) [inline src/DefinitionResolver.php]: Leading/trailing whitespace is already gone by this point, this is handling a specific case.

File: src/CompletionProvider.php (hunk 41 above)
Comment (roblourens) [inline src/CompletionProvider.php]: Sure. Are anonymous functions slow in PHP or is it a style preference.

Comment (felixfbecker) [inline src/CompletionProvider.php]: They are slow unfortunately. The variable actually becomes an instance of `Closure`, which has `__invoke()` defined. The difference is significant when comparing e.g. `array_map` with callback to an equivalent `foreach` loop.

Comment (roblourens) [inline src/CompletionProvider.php]: Ok. After messing around with callables for a bit, I'm actually confused about the right way to do this in PHP. Either it's a method on `CompletionProvider` which I reference as `array($this, 'functionName')`, in which case it has to be public, which seems not great. Or if it's a function declared outside the class, which I just reference with a string. When I try that, I get the error `Error: Call to undefined function isAssignmentToVariable()`, I guess because it's not in scope in Node.php.

Comment (felixfbecker) [inline src/CompletionProvider.php]: Functions must be referenced by their fully qualified name, including namespace. E.g. `$node->getDescendantNodes('LanguageServer\\isNotFunctionLike')`.
Tbh I didn't see that you are passing it as a callback, I just saw that `isAssignmentToVariable` is called directly in L417 and L421. I would move `isAssignmentToVariable` to a private method and would be okay with leaving `isNotFunctionLike` as-is.

**Comment by jens1o** [comment]
I found a critical bug:
```
[Error - 1:22:42 PM] Request textDocument/completion failed.
  Message: Error: Call to a member function getValues() on null in C:\Users\Jens\.vscode\extensions\felixfbecker.php-intellisense-1.2.2\vendor\felixfbecker\language-server\src\CompletionProvider.php:380
Stack trace:
#0 C:\Users\Jens\.vscode\extensions\felixfbecker.php-intellisense-1.2.2\vendor\felixfbecker\language-server\src\CompletionProvider.php(163): LanguageServer\CompletionProvider->suggestVariablesAtNode(Object(Microsoft\PhpParser\Node\Expression\Variable), '')
#1 C:\Users\Jens\.vscode\extensions\felixfbecker.php-intellisense-1.2.2\vendor\felixfbecker\language-server\src\Server\TextDocument.php(346): LanguageServer\CompletionProvider->provideCompletion(Object(LanguageServer\PhpDocument), Object(LanguageServer\Protocol\Position))
#2 [internal function]: LanguageServer\Server\TextDocument->LanguageServer\Server\{closure}()
#3 C:\Users\Jens\.vscode\extensions\felixfbecker.php-intellisense-1.2.2\vendor\sabre\event\lib\coroutine.php(70): Generator->send(Object(LanguageServer\PhpDocument))
#4 C:\Users\Jens\.vscode\extensions\felixfbecker.php-intellisense-1.2.2\vendor\sabre\event\lib\Promise.php(242): Sabre\Event\{closure}(Object(LanguageServer\PhpDocument))
#5 C:\Users\Jens\.vscode\extensions\felixfbecker.php-intellisense-1.2.2\vendor\sabre\event\lib\Loop\Loop.php(261): Sabre\Event\Promise->Sabre\Event\{closure}()
#6 C:\Users\Jens\.vscode\extensions\felixfbecker.php-intellisense-1.2.2\vendor\sabre\event\lib\Loop\Loop.php(215): Sabre\Event\Loop\Loop->runNextTicks()
#7 C:\Users\Jens\.vscode\extensions\felixfbecker.php-intellisense-1.2.2\vendor\sabre\event\lib\Loop\Loop.php(194): Sabre\Event\Loop\Loop->tick(true)
#8 C:\Users\Jens\.vscode\extensions\felixfbecker.php-intellisense-1.2.2\vendor\sabre\event\lib\Loop\functions.php(122): Sabre\Event\Loop\Loop->run()
#9 C:\Users\Jens\.vscode\extensions\felixfbecker.php-intellisense-1.2.2\vendor\felixfbecker\language-server\bin\php-language-server.php(50): Sabre\Event\Loop\run()
#10 {main}
  Code: -32603 
```

Happens here: 
image
When I change the `callback` to a `closure`:
image
As soon as I type the `$`, it pops up.

Code:
```php
<?php
// lang block plugin
$smarty->registerPlugin('block', 'lang', function ($params, $content) use ($logger) {
        if(isset($content)) {
        }
});

**Comment by jens1o** [comment]
After that, this error pops up around twice a minute.
```
[Error - 1:31:03 PM] Request textDocument/completion failed.
  Message: Error: Call to a member function getLastChild() on null in C:\Users\Jens\.vscode\extensions\felixfbecker.php-intellisense-1.2.2\vendor\felixfbecker\language-server\src\CompletionProvider.php:131
Stack trace:
#0 C:\Users\Jens\.vscode\extensions\felixfbecker.php-intellisense-1.2.2\vendor\felixfbecker\language-server\src\Server\TextDocument.php(346): LanguageServer\CompletionProvider->provideCompletion(Object(LanguageServer\PhpDocument), Object(LanguageServer\Protocol\Position))
#1 [internal function]: LanguageServer\Server\TextDocument->LanguageServer\Server\{closure}()
#2 C:\Users\Jens\.vscode\extensions\felixfbecker.php-intellisense-1.2.2\vendor\sabre\event\lib\coroutine.php(70): Generator->send(Object(LanguageServer\PhpDocument))
#3 C:\Users\Jens\.vscode\extensions\felixfbecker.php-intellisense-1.2.2\vendor\sabre\event\lib\Promise.php(242): Sabre\Event\{closure}(Object(LanguageServer\PhpDocument))
#4 C:\Users\Jens\.vscode\extensions\felixfbecker.php-intellisense-1.2.2\vendor\sabre\event\lib\Loop\Loop.php(261): Sabre\Event\Promise->Sabre\Event\{closure}()
#5 C:\Users\Jens\.vscode\extensions\felixfbecker.php-intellisense-1.2.2\vendor\sabre\event\lib\Loop\Loop.php(215): Sabre\Event\Loop\Loop->runNextTicks()
#6 C:\Users\Jens\.vscode\extensions\felixfbecker.php-intellisense-1.2.2\vendor\sabre\event\lib\Loop\Loop.php(194): Sabre\Event\Loop\Loop->tick(true)
#7 C:\Users\Jens\.vscode\extensions\felixfbecker.php-intellisense-1.2.2\vendor\sabre\event\lib\Loop\functions.php(122): Sabre\Event\Loop\Loop->run()
#8 C:\Users\Jens\.vscode\extensions\felixfbecker.php-intellisense-1.2.2\vendor\felixfbecker\language-server\bin\php-language-server.php(50): Sabre\Event\Loop\run()
#9 {main}
  Code: -32603 
```

But I don't know what causes it, although it's the same project.

**Comment by jens1o** [comment]
After some hours coding, I get this error and after this, the extension host stops working:
image

**Comment by jens1o** [comment]
Random error:
```
[Error - 1:39:40 PM] Request textDocument/completion failed.
  Message: TypeError: ltrim() expects parameter 1 to be string, boolean given in C:\Users\Jens\.vscode\extensions\felixfbecker.php-intellisense-1.2.2\vendor\felixfbecker\language-server\src\DefinitionResolver.php:1195
Stack trace:
#0 C:\Users\Jens\.vscode\extensions\felixfbecker.php-intellisense-1.2.2\vendor\felixfbecker\language-server\src\DefinitionResolver.php(1195): ltrim(false, '$')
#1 C:\Users\Jens\.vscode\extensions\felixfbecker.php-intellisense-1.2.2\vendor\felixfbecker\language-server\src\DefinitionResolver.php(110): LanguageServer\DefinitionResolver->tryGetDocBlockTagForParameter(Object(phpDocumentor\Reflection\DocBlock), false)
#2 C:\Users\Jens\.vscode\extensions\felixfbecker.php-intellisense-1.2.2\vendor\felixfbecker\language-server\src\CompletionProvider.php(167): LanguageServer\DefinitionResolver->getDocumentationFromNode(Object(Microsoft\PhpParser\Node\Parameter))
#3 C:\Users\Jens\.vscode\extensions\felixfbecker.php-intellisense-1.2.2\vendor\felixfbecker\language-server\src\Server\TextDocument.php(346): LanguageServer\CompletionProvider->provideCompletion(Object(LanguageServer\PhpDocument), Object(LanguageServer\Protocol\Position))
#4 [internal function]: LanguageServer\Server\TextDocument->LanguageServer\Server\{closure}()
#5 C:\Users\Jens\.vscode\extensions\felixfbecker.php-intellisense-1.2.2\vendor\sabre\event\lib\coroutine.php(70): Generator->send(Object(LanguageServer\PhpDocument))
#6 C:\Users\Jens\.vscode\extensions\felixfbecker.php-intellisense-1.2.2\vendor\sabre\event\lib\Promise.php(242): Sabre\Event\{closure}(Object(LanguageServer\PhpDocument))
#7 C:\Users\Jens\.vscode\extensions\felixfbecker.php-intellisense-1.2.2\vendor\sabre\event\lib\Loop\Loop.php(261): Sabre\Event\Promise->Sabre\Event\{closure}()
#8 C:\Users\Jens\.vscode\extensions\felixfbecker.php-intellisense-1.2.2\vendor\sabre\event\lib\Loop\Loop.php(215): Sabre\Event\Loop\Loop->runNextTicks()
#9 C:\Users\Jens\.vscode\extensions\felixfbecker.php-intellisense-1.2.2\vendor\sabre\event\lib\Loop\Loop.php(194): Sabre\Event\Loop\Loop->tick(true)
#10 C:\Users\Jens\.vscode\extensions\felixfbecker.php-intellisense-1.2.2\vendor\sabre\event\lib\Loop\functions.php(122): Sabre\Event\Loop\Loop->run()
#11 C:\Users\Jens\.vscode\extensions\felixfbecker.php-intellisense-1.2.2\vendor\felixfbecker\language-server\bin\php-language-server.php(50): Sabre\Event\Loop\run()
#12 {main}
  Code: -32603 
```
While adding typehint in a function.

File: src/DefinitionResolver.php [hunk 43]
```diff
@@ -70,35 +86,77 @@ public function getDeclarationLineFromNode(Node $node): string
...
+            if ($namespaceDefinition !== null && $namespaceDefinition->name !== null) {
+                $namespaceName = (string)$namespaceDefinition->name->getNamespacedName();
+            } else {
+                $namespaceName = 'global';
+            }
+            $context = new Types\Context($namespaceName, $namespaceImportTable);
+
+            try {
+                return $this->docBlockFactory->create($docCommentText, $context);
+            } catch (\InvalidArgumentException $e) {
```
Comment (roblourens) [inline src/DefinitionResolver.php]: I see it thrown a few times if I remove the try/catch. One example: a doccomment line in the cakephp project source is:

`* @see config/app.php for configuration settings`

We pass all the docCommentText, and the factory throws because config/app.php is not a valid fqsen. That seems like the wrong thing for phpdocumentor to do? I don't think we can validate it before passing it in. I'll add a comment though.

File: src/DefinitionResolver.php [hunk 44]
```diff
@@ -108,37 +166,60 @@ public function getDocumentationFromNode(Node $node)
      * @param string $fqn
      * @return Definition
      */
-    public function createDefinitionFromNode(Node $node, string $fqn = null): Definition
+    public function createDefinitionFromNode($node, string $fqn = null): Definition
```
Comment (roblourens) [inline src/DefinitionResolver.php]: Sure

File: src/DefinitionResolver.php (hunk 43 above)
Comment (felixfbecker) [inline src/DefinitionResolver.php]: It is a long-standing bug for the `@see` tag to only accept FQSENs, but not for other tags.
These errors are reported as diagnostics in master:
https://sourcegraph.com/github.com/felixfbecker/php-language-server/-/blob/src/NodeVisitor/DocBlockParser.php#L77-78
https://sourcegraph.com/github.com/felixfbecker/php-language-server/-/blob/src/NodeVisitor/DocBlockParser.php#L77-78

File: src/DefinitionResolver.php [hunk 45]
```diff
@@ -108,37 +166,60 @@ public function getDocumentationFromNode(Node $node)
...
-                $def->extends[] = (string)$node->extends;
-            }
-        } else if ($node instanceof Node\Stmt\Interface_) {
+
+        if ($node instanceof Node\Statement\ClassDeclaration &&
+            // TODO - this should be bette rrpreented in the parser API
+            $node->classBaseClause !== null && $node->classBaseClause->baseClass !== null) {
+            $def->extends = [(string)$node->classBaseClause->baseClass->getResolvedName()];
+            // TODO - why is this represented as an array?
+            // TODO interface implementations.
```
Comment (roblourens) [inline src/DefinitionResolver.php]: If they just need to be added to the `extends` array, then I don't think so.

File: src/DefinitionResolver.php (hunk 43 above)
Comment (roblourens) [inline src/DefinitionResolver.php]: I see, there is a todo for that: https://github.com/felixfbecker/php-language-server/pull/357/files#diff-5dbc7bc13d1b3b19cbf8780c2f72f174R41

I'll add it to the list. Might make sense to handle as an issue out of the PR.

File: src/DefinitionResolver.php (hunk 45 above)
Comment (roblourens) [inline src/DefinitionResolver.php]: It works, but then it doesn't match the old behavior. Then if I have `class C implements I`, and `I` has some methods that `C` implements, then they show up twice in completions. Unless we dedupe completions somewhere, it kind of seems right to ignore the implemented interfaces.

The current behavior seems to match that of the old parser. Side note, if a class overrides a base class' method, then that shows up twice, for probably the same reason.

File: src/FqnUtilities.php (hunk 18 above)
Comment (roblourens) [inline src/FqnUtilities.php]: Only one I can think of is that to use a file of pure functions from another namespace, you have to import them individually. Is there a way around that?

https://github.com/felixfbecker/php-language-server/blob/master/src/FilesFinder/FileSystemFilesFinder.php#L9

Putting them in a class gives you one thing to import?

File: src/Index/Index.php (hunk 19 above)
Comment (roblourens) [inline src/Index/Index.php]: Changed for ValidationTest, but that's not necessary. Will fix

File: src/DefinitionResolver.php (hunk 43 above)
Comment (felixfbecker) [inline src/DefinitionResolver.php]: Sounds good! thanks for adding the comment

File: src/FqnUtilities.php (hunk 18 above)
Comment (felixfbecker) [inline src/FqnUtilities.php]: Sure, you could also refer them by their namespace just like you would refer to a static class, e.g.
```php
namespace LanguageServer\FqnUtilities;
function foo() {}
```
```php
namespace LanguageServer;
FqnUtilities\foo();
```
Aliasing them is just for being able to omit the prefix (if the function name is clear enough).

The file just needs to be added to composer.jsons `autoload.files` array.

**Comment by felixfbecker** [comment]
@roblourens are you still working on a major bug or just the few minor comments that are left? I would be up to merging this tomorrow 👍

**Comment by jens1o** [comment]
I think there should be a beta first, so the user do not have a bad experience to verify that all problems have been solved.

**Comment by felixfbecker** [comment]
@jens1o there will be a prerelease.

**Comment by jens1o** [comment]
I'm not sure whether this concerns this pr, but the language server has problems computing a cache key for `microsoft/tolerant-php-parser` when being set up like this: https://github.com/Microsoft/tolerant-php-parser/blob/master/docs/GettingStarted.md#ready-set-parse

File: src/ParserHelpers.php [hunk 46]
```diff
@@ -0,0 +1,128 @@
...
+     * @return bool
+     */
+    public static function isConstDefineExpression(Node $node): bool
+    {
+        return $node instanceof Node\Expression\CallExpression
+            && $node->callableExpression instanceof Node\QualifiedName
+            && strtolower($node->callableExpression->getText()) === 'define'
+            && isset($node->argumentExpressionList->children[0])
+            && $node->argumentExpressionList->children[0]->expression instanceof Node\StringLiteral
+            && isset($node->argumentExpressionList->children[2]);
```
Comment (jens1o) [inline src/ParserHelpers.php]: maybe check whether this is not an instance of `MissingToken`?

**Comment by felixfbecker** [comment]
> I'm not sure whether this concerns this pr, but the language server has problems computing a cache key for microsoft/tolerant-php-parser when being set up like this: https://github.com/Microsoft/tolerant-php-parser/blob/master/docs/GettingStarted.md#ready-set-parse

This is as designed and will be fixed once @roblourens publishes on packagist.org

File: src/Protocol/SymbolInformation.php [hunk 47]
```diff
@@ -44,66 +45,80 @@ class SymbolInformation
...
+        } else if ($node instanceof Node\Statement\FunctionDeclaration) {
             $symbol->kind = SymbolKind::FUNCTION;
-        } else if ($node instanceof Node\Stmt\ClassMethod && ($node->name === '__construct' || $node->name === '__destruct')) {
-            $symbol->kind = SymbolKind::CONSTRUCTOR;
-        } else if ($node instanceof Node\Stmt\ClassMethod) {
-            $symbol->kind = SymbolKind::METHOD;
-        } else if ($node instanceof Node\Stmt\PropertyProperty) {
+        } else if ($node instanceof Node\MethodDeclaration) {
+            $nameText = $node->getName();
+            if ($nameText  === '__construct' || $nameText === '__destruct') {
```
Comment (jens1o) [inline src/Protocol/SymbolInformation.php]: Codestyle: One space more than needed in the construct check

File: src/CompletionProvider.php [hunk 48]
```diff
@@ -121,45 +123,71 @@ public function __construct(DefinitionResolver $definitionResolver, ReadableInde
...
     public function provideCompletion(PhpDocument $doc, Position $pos): CompletionList
     {
+        // This can be made much more performant if the tree follows specific invariants.
         $node = $doc->getNodeAtPosition($pos);
 
-        if ($node instanceof Node\Expr\Error) {
-            $node = $node->getAttribute('parentNode');
+        $offset = $node === null ? -1 : $pos->toOffset($node->getFileContents());
+        if ($node !== null && $offset > $node->getEndPosition() &&
+            $node->parent->getLastChild() instanceof PhpParser\MissingToken
```
Comment (jens1o) [inline src/CompletionProvider.php]: You should check whether the node has a parent first to resolve a bug I noticed.

File: src/DefinitionResolver.php [hunk 49]
```diff
@@ -655,54 +849,68 @@ public function resolveExpressionNodeToType(Node\Expr $expr): Type
...
         return new Types\Mixed;
     }
 
+
     /**
      * Takes any class name node (from a static method call, or new node) and returns a Type object
      * Resolves keywords like self, static and parent
      *
-     * @param Node $class
+     * @param Node || PhpParser\Token $class
```
Comment (jens1o) [inline src/DefinitionResolver.php]: why `||`?

File: src/DefinitionResolver.php [hunk 50]
```diff
@@ -843,67 +1058,138 @@ public function getTypeFromNode(Node $node)
...
+            $node instanceof Node\Statement\TraitDeclaration
+        ) {
+            return (string) $node->getNamespacedName();
+        }
+
+        // INPUT                   OUTPUT:
+        // namespace A\B;           A\B
+        if ($node instanceof Node\Statement\NamespaceDefinition && $node->name instanceof Node\QualifiedName) {
+            $name = (string) PhpParser\ResolvedName::buildName($node->name->nameParts, $node->getFileContents());
+            return \count($name) > 0 ? $name : null;
```
Comment (jens1o) [inline src/DefinitionResolver.php]: what does this do? How can we count a string?

File: src/ParserHelpers.php (hunk 22 above)
Comment (roblourens) [inline src/ParserHelpers.php]: It's not needed anymore

File: src/Server/TextDocument.php (hunk 27 above)
Comment (roblourens) [inline src/Server/TextDocument.php]: I don't know if Sara ran a formatter or something that undid the alignment. I can revert it if you prefer.

File: src/utils.php (hunk 32 above)
Comment (roblourens) [inline src/utils.php]: I find it easier to read with a helper function, especially since prefix is duplicated. Using substr would be a better implementation though.

Comment (felixfbecker) [inline src/utils.php]: While it is definitely more readable, function invocations have a considerable overhead in PHP compared to other languages, so I would avoid them if it's a one-liner.

**Comment by roblourens** [comment]
> @roblourens are you still working on a major bug or just the few minor comments that are left? I would be up to merging this tomorrow 👍

Just working through the rest of the comments. I'm definitely 👍 on merging tomorrow. I've been focusing on our upcoming release the past week but should be able to focus on this for the rest of today.

File: tests/Validation/ValidationTest.php (hunk 38 above)
Comment (roblourens) [inline tests/Validation/ValidationTest.php]: Added a comment, made the test name better, and cleaned it up some more.

I think this is an easy and powerful way to write tests for some cases, but not every case. With a little work, it could be extended to test more scenarios with this strategy.

File: tests/Validation/ValidationTest.php (hunk 35 above)
Comment (roblourens) [inline tests/Validation/ValidationTest.php]: The real problem is that the real objects are instances of some class, and I need to compare them to values parsed from json. I could write a deserialize method for Definition, probably not worth it.

File: composer.json [hunk 51]
```diff
@@ -38,9 +37,16 @@
...
+        "composer/composer": "^1.3",
+        "Microsoft/tolerant-php-parser": "dev-master"
     },
     "minimum-stability": "dev",
+    "repositories": [
+        {
+            "type": "git",
+            "url": "https://github.com/Microsoft/tolerant-php-parser.git"
+        }
+    ],
```
Comment (jens1o) [inline composer.json]: Is this still true, because you want to merge it tomorrow? :/

File: tests/Validation/ValidationTest.php (hunk 37 above)
Comment (roblourens) [inline tests/Validation/ValidationTest.php]: I think this was just to smooth over known differences between the two DefinitionResolvers. It shouldn't be needed for the tests now, removed.

File: tests/Validation/ValidationTest.php (hunk 35 above)
Comment (felixfbecker) [inline tests/Validation/ValidationTest.php]: ah, gotcha. JSON encoding+decoding is actually the easiest way to do this, I struggled with this too.

File: src/DefinitionResolver.php (hunk 50 above)
Comment (roblourens) [inline src/DefinitionResolver.php]: I assume `strlen` was intended, good catch.

Comment (felixfbecker) [inline src/DefinitionResolver.php]: I this case, it should just be `$name === ""`

File: composer.json (hunk 51 above)
Comment (roblourens) [inline composer.json]: I plan to look at this today :)

**Comment by roblourens** [comment]
I've fixed all the reported errors that needed immediate fixing (thanks @jens1o!) and I'll publish an updated version of the extension when I can - I'm just having trouble with composer right now because it can't contact the Packagist server or something.

I also will publish the parser on Packagist, but the microsoft namespace is protected and I need to figure out how to get access.

Besides that, I think everything else can be addressed via issues later.

File: src/CompletionProvider.php [hunk 52]
```diff
@@ -420,10 +420,10 @@ private function findVariableDefinitionsInNode(Node $node, string $namePrefix =
         return $vars;
     }
 
-    private function isAssignmentToVariableWithPrefix($node, $namePrefix)
+    private function isAssignmentToVariableWithPrefix(Node $node, string $namePrefix): bool
     {
         return $node instanceof Node\Expression\AssignmentExpression
             && $node->leftOperand instanceof Node\Expression\Variable
-            && (empty($namePrefix) || strpos($node->leftOperand->getName(), $namePrefix) !== false);
+            && ($namePrefix === '' || strpos($node->leftOperand->getName(), $namePrefix) !== false);
```
Comment (jens1o) [inline src/CompletionProvider.php]: should we consider updating this everywhere to improve performance?

**Comment by roblourens** [comment]
Here's the latest:

[php-intellisense-1.3.0.txt](https://github.com/felixfbecker/php-language-server/files/1061625/php-intellisense-1.3.0.txt)

Again, rename from txt to vsix.

File: src/CompletionProvider.php (hunk 52 above)
Comment (felixfbecker) [inline src/CompletionProvider.php]: yes, but it's not so important.

**Comment by jens1o** [comment]
Somehow it breaks intellisense completely. I don't get any intellisense when using a method.

No matter how I say it's the specific type... No matter whether it is static or not...

Example: https://github.com/jens1o/smashcast-api-php/blob/master/tests/SmashcastApiTest.php#L51

Clone that repo, install the dependencies and try to get out what `$client` is. Hint: It is not `mixed`. :/
image

**Comment by roblourens** [comment]
Is this recent @jens1o? I don't think it worked earlier with the new parser. Should definitely be addressed.

**Comment by jens1o** [comment]
No, it's not. Actually, I reported that earlier, https://github.com/felixfbecker/php-language-server/pull/357#issuecomment-305742033 but there were no reaction, so I looked up to provide sure reproducing steps before you publish this.

**Comment by roblourens** [comment]
This PR is definitely big enough to lose things in. Another reason to close it out 😁

**Comment by jens1o** [comment]
Don't know whether this affects this pr or will be added in the future, but just a notice:
image
`$response` won't be registered: https://github.com/jens1o/smashcast-api-php/blob/master/src/channel/SmashcastChannel.php#L219

**Comment by jens1o** [comment]
Another notice:
image
When searching for references for a function call, the signature won't be marked, too.

**Comment by roblourens** [comment]
We should open an issue for that one too after this is merged @jens1o.

I published the parser on Packagist (https://packagist.org/packages/microsoft/tolerant-php-parser), and just pushed a change to pull that in, instead of referencing github. So the PR is good to go from my end. @felixfbecker?

**Comment by jens1o** [comment]
Okay.

File: src/CompletionProvider.php [hunk 53]
```diff
@@ -169,122 +197,112 @@ public function provideCompletion(PhpDocument $doc, Position $pos): CompletionLi
...
+                                    $fqn = $alias;
+                                    $isAliased = true;
+                                    break;
+                                }
+                            }
+                        }
+
+
+                        if (!$isNotFullyQualified && ($fqnStartsWithPrefix || strStartsWith($fqn, $namespacePrefix . "\\" . $prefix))) {
+                            // $fqn = $fqn;
```
Comment (felixfbecker) [inline src/CompletionProvider.php]: What is this? Can the `if` be combined with the condition in the `elseif`?

**Comment by felixfbecker** [comment]
@roblourens Should the validation tests be run in CI too?

**Comment by felixfbecker** [comment]
I don't have any objections to merging otherwise. Could you open issues for the things that need to be done as a followup?

File: src/CompletionProvider.php (hunk 53 above)
Comment (roblourens) [inline src/CompletionProvider.php]: That could be better, this also reminds me that I was going to inline strStartsWith.

**Comment by felixfbecker** [comment]
Cool, I assumed there were some extra steps needed to make the submodules work in Travis, but looks fine!

**Comment by roblourens** [comment]
At the moment, the submodules would only be used for the Performance test. ValidationTest only runs on the individual testcases in the cases/ folder (previously, it ran on the submodules comparing the result to the old parser).

**Comment by roblourens** [comment]
I will file a whole bunch of issues shortly. Are you waiting for that before merging? Or also the latest comment https://github.com/felixfbecker/php-language-server/pull/357#discussion_r121106444?

**Comment by felixfbecker** [comment]
I was going to fix https://github.com/felixfbecker/php-language-server/pull/357#discussion_r121106444 before merging, but if you want to do it quick feel free to do so

**Comment by roblourens** [comment]
Those conditions are a little gnarly... it's not pretty but it will work the same now

**Comment by felixfbecker** [comment]
Simplified the condition further :)

File: Performance.php [hunk 54]
```diff
@@ -0,0 +1,71 @@
...
+            $testProviderArray[] = $file->getPathname();
+        }
+    }
+
+    if (count($testProviderArray) === 0) {
+        throw new Exception("ERROR: Validation testsuite frameworks not found - run `git submodule update --init --recursive` to download.");
+    }
+
+
+    $parserKinds = [ParserKind::PHP_PARSER, ParserKind::TOLERANT_PHP_PARSER];
```
Comment (felixfbecker) [inline Performance.php]: Does ParserKind still exist?

Comment (roblourens) [inline Performance.php]: Damnit, one sec :)

**Comment by felixfbecker** [comment]
IT'S DONE 🎉
Thanks to everyone who contributed to this! This is a milestone

**Comment by jens1o** [comment]
Thanks... is that even a word? :/

**Comment by roblourens** [comment]
@felixfbecker It might be useful to have the history of this PR, since so much happened, instead of squashing? I understand wanting a clean history, but `git blame` will be more useful if we can see all the commit messages. Up to you.

**Comment by jens1o** [comment]
I agree with @roblourens

**Comment by felixfbecker** [comment]
@roblourens I didn't want to have all the cleanup commits in there, but doing a manual rebase sounded like a lot of work... You are right but I don't think it's worth force pushing master now

**Comment by felixfbecker** [comment]
I usually only rebase+merge or merge with merge commit if every commit passes tests on its own and could be reverted on its own, which would have been hard to ensure for all the commits in this PR.
